\ NovaForth wrappers for the NDK FILES module.
\ Standard ANS file words live in forth/lib/file.4th. These FILES-* words expose
\ Nova's file-domain NDK calls without shadowing the standard word set.

INCLUDE forth/lib/nova/ndk.4th

BASE @
DECIMAL

0 CONSTANT FILES-FN-SAVE
1 CONSTANT FILES-FN-LOAD
2 CONSTANT FILES-FN-DIR-OPEN
3 CONSTANT FILES-FN-DIR-READ
4 CONSTANT FILES-FN-DELETE
5 CONSTANT FILES-FN-GSAVE
6 CONSTANT FILES-FN-GLOAD
7 CONSTANT FILES-FN-CD
8 CONSTANT FILES-FN-MKDIR
9 CONSTANT FILES-FN-RMDIR
10 CONSTANT FILES-FN-PWD
11 CONSTANT FILES-FN-LOAD-RUNTIME
12 CONSTANT FILES-FN-RUN
13 CONSTANT FILES-FN-RNG
14 CONSTANT FILES-FN-PAGE
15 CONSTANT FILES-FN-FOPEN
16 CONSTANT FILES-FN-FCREATE
17 CONSTANT FILES-FN-FCLOSE
18 CONSTANT FILES-FN-FREAD
19 CONSTANT FILES-FN-FWRITE
20 CONSTANT FILES-FN-FSEEK
21 CONSTANT FILES-FN-FTELL
22 CONSTANT FILES-FN-FSIZE
23 CONSTANT FILES-FN-FRESIZE
24 CONSTANT FILES-FN-FFLUSH
25 CONSTANT FILES-FN-FSTATUS
26 CONSTANT FILES-FN-FDELETE
27 CONSTANT FILES-FN-FRENAME
28 CONSTANT FILES-FN-DIR-LIST
29 CONSTANT FILES-FN-COUNT

HEX
B9A0 CONSTANT FIO-CMD-REG
B9A1 CONSTANT FIO-STATUS
B9A2 CONSTANT FIO-ERRCODE
B9A3 CONSTANT FIO-NAMELEN
B9A4 CONSTANT FIO-SRCL
B9A5 CONSTANT FIO-SRCH
B9A6 CONSTANT FIO-ENDL
B9A7 CONSTANT FIO-ENDH
B9A8 CONSTANT FIO-SIZEL
B9A9 CONSTANT FIO-SIZEH
B9AA CONSTANT FIO-SIZE2
B9AA CONSTANT FIO-GSPACE
B9AB CONSTANT FIO-GADDRL
B9AC CONSTANT FIO-GADDRH
B9AD CONSTANT FIO-GLENL
B9AE CONSTANT FIO-GLENH
B9AF CONSTANT FIO-DIRTYPE
B9B0 CONSTANT FIO-NAME

01 CONSTANT FIO-CMD-SAVE
02 CONSTANT FIO-CMD-LOAD
03 CONSTANT FIO-CMD-DIROPEN
04 CONSTANT FIO-CMD-DIRREAD
05 CONSTANT FIO-CMD-DELETE
06 CONSTANT FIO-CMD-GSAVE
07 CONSTANT FIO-CMD-GLOAD
20 CONSTANT FIO-CMD-CD
21 CONSTANT FIO-CMD-MKDIR
22 CONSTANT FIO-CMD-RMDIR
26 CONSTANT FIO-CMD-PWD
27 CONSTANT FIO-CMD-CLEARERR
28 CONSTANT FIO-CMD-LOADRUNTIME
29 CONSTANT FIO-CMD-XPAGE
2A CONSTANT FIO-CMD-RNG
2B CONSTANT FIO-CMD-NVGLOAD
2C CONSTANT FIO-CMD-LOAD-MODULE
2D CONSTANT FIO-CMD-FOPEN
2E CONSTANT FIO-CMD-FCREATE
2F CONSTANT FIO-CMD-FCLOSE
30 CONSTANT FIO-CMD-FREAD
31 CONSTANT FIO-CMD-FWRITE
32 CONSTANT FIO-CMD-FSEEK
33 CONSTANT FIO-CMD-FTELL
34 CONSTANT FIO-CMD-FSIZE
35 CONSTANT FIO-CMD-FRESIZE
36 CONSTANT FIO-CMD-FFLUSH
37 CONSTANT FIO-CMD-FSTATUS
38 CONSTANT FIO-CMD-FDELETE
39 CONSTANT FIO-CMD-FRENAME

00 CONSTANT FIO-STATUS-IDLE
02 CONSTANT FIO-STATUS-OK
03 CONSTANT FIO-STATUS-ERROR

00 CONSTANT FIO-ERR-NONE
01 CONSTANT FIO-ERR-NOTFOUND
02 CONSTANT FIO-ERR-IO
03 CONSTANT FIO-ERR-EOD
04 CONSTANT FIO-ERR-DISKFULL
05 CONSTANT FIO-ERR-NOTMOUNTED

00 CONSTANT FIO-TYPE-BAS
01 CONSTANT FIO-TYPE-SID
02 CONSTANT FIO-TYPE-BIN
03 CONSTANT FIO-TYPE-MID
04 CONSTANT FIO-TYPE-GFX
05 CONSTANT FIO-TYPE-DIR
06 CONSTANT FIO-TYPE-FORTH
07 CONSTANT FIO-TYPE-LOGO

00 CONSTANT PAGER-TARGET-XRAM
01 CONSTANT PAGER-TARGET-RAM
02 CONSTANT PAGER-TARGET-VGC
DECIMAL

: FILES-CALL ( fn -- ior )
  MODULE-FILES SWAP NOVA-LIBCALL ;

: FILES-NAME! ( c-addr u -- )
  LIB-ARG1 ! LIB-ARG0 ! ;

: FILES-GFX! ( space gaddr glen -- )
  LIB-ARG3 ! LIB-ARG2 1 + ! LIB-ARG2 C! ;

: FILES-NAME ( -- c-addr u )
  FIO-NAME FIO-NAMELEN C@ ;

: FILES-STATUS ( -- status )
  FIO-STATUS C@ ;

: FILES-ERRCODE ( -- err )
  FIO-ERRCODE C@ ;

: FILES-DIR-TYPE ( -- type )
  FIO-DIRTYPE C@ ;

: FILES-DIR-SIZE ( -- lo hi )
  FIO-SIZEL @ FIO-SIZE2 C@ ;

: FILES-SAVE ( c-addr u src end -- ior )
  LIB-ARG3 ! LIB-ARG2 ! FILES-NAME!
  FILES-FN-SAVE FILES-CALL ;

: FILES-LOAD ( c-addr u dest -- ior )
  LIB-ARG2 ! FILES-NAME!
  FILES-FN-LOAD FILES-CALL ;

: FILES-DIR-OPEN ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-DIR-OPEN FILES-CALL ;

: FILES-DIR-OPEN-ALL ( -- ior )
  0 0 FILES-DIR-OPEN ;

: FILES-DIR-READ ( -- ior )
  FILES-FN-DIR-READ FILES-CALL ;

: FILES-DELETE ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-DELETE FILES-CALL ;

: FILES-GSAVE ( c-addr u space gaddr glen -- ior )
  FILES-GFX! FILES-NAME!
  FILES-FN-GSAVE FILES-CALL ;

: FILES-GLOAD ( c-addr u space gaddr glen -- ior )
  FILES-GFX! FILES-NAME!
  FILES-FN-GLOAD FILES-CALL ;

: FILES-CD ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-CD FILES-CALL ;

: FILES-MKDIR ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-MKDIR FILES-CALL ;

: FILES-RMDIR ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-RMDIR FILES-CALL ;

: FILES-PWD ( -- c-addr u ior )
  FILES-FN-PWD FILES-CALL >R FILES-NAME R> ;

: FILES-LOAD-RUNTIME ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-LOAD-RUNTIME FILES-CALL ;

: FILES-RUN ( cmd -- ior )
  LIB-ARG0 C!
  FILES-FN-RUN FILES-CALL ;

: FILES-RNG ( -- lo hi ior )
  FILES-FN-RNG FILES-CALL >R NDK-RESULT32 R> ;

: FILES-PAGE ( c-addr u offlo offhi target destlo desthi len -- ior )
  LIB-ARG3 !
  LIB-ARG2 NDK-U24!
  LIB-ARG1 3 + C!
  LIB-ARG1 NDK-U24!
  LIB-ARG0 NDK-BYTES8!
  FILES-FN-PAGE FILES-CALL ;

: FILES-FOPEN ( c-addr u fam -- fileid ior )
  LIB-ARG2 ! FILES-NAME!
  FILES-FN-FOPEN FILES-CALL NDK-RESULT16 SWAP ;

: FILES-FCREATE ( c-addr u fam -- fileid ior )
  LIB-ARG2 ! FILES-NAME!
  FILES-FN-FCREATE FILES-CALL NDK-RESULT16 SWAP ;

: FILES-FCLOSE ( fileid -- ior )
  LIB-ARG0 !
  FILES-FN-FCLOSE FILES-CALL ;

: FILES-FREAD ( c-addr u fileid -- u2 ior )
  LIB-ARG0 ! LIB-ARG2 ! LIB-ARG1 !
  FILES-FN-FREAD FILES-CALL NDK-RESULT16 SWAP ;

: FILES-FWRITE ( c-addr u fileid -- u2 ior )
  LIB-ARG0 ! LIB-ARG2 ! LIB-ARG1 !
  FILES-FN-FWRITE FILES-CALL NDK-RESULT16 SWAP ;

: FILES-FSEEK ( ud fileid -- ior )
  LIB-ARG0 ! LIB-ARG1 2 + C! LIB-ARG1 !
  FILES-FN-FSEEK FILES-CALL ;

: FILES-FTELL ( fileid -- ud ior )
  LIB-ARG0 !
  FILES-FN-FTELL FILES-CALL >R NDK-RESULT24 R> ;

: FILES-FSIZE ( fileid -- ud ior )
  LIB-ARG0 !
  FILES-FN-FSIZE FILES-CALL >R NDK-RESULT24 R> ;

: FILES-FRESIZE ( ud fileid -- ior )
  LIB-ARG0 ! LIB-ARG1 2 + C! LIB-ARG1 !
  FILES-FN-FRESIZE FILES-CALL ;

: FILES-FFLUSH ( fileid -- ior )
  LIB-ARG0 !
  FILES-FN-FFLUSH FILES-CALL ;

: FILES-FSTATUS ( c-addr u -- fam ior )
  FILES-NAME!
  FILES-FN-FSTATUS FILES-CALL NDK-RESULT16 SWAP ;

: FILES-FDELETE ( c-addr u -- ior )
  FILES-NAME!
  FILES-FN-FDELETE FILES-CALL ;

: FILES-FRENAME ( c-addr1 u1 c-addr2 u2 -- ior )
  LIB-ARG3 ! LIB-ARG2 ! FILES-NAME!
  FILES-FN-FRENAME FILES-CALL ;

\ FILES-DIR-LIST ( c-addr u -- ior ): the host prints a formatted NAME/TYPE/SIZE
\ listing of the directory named by c-addr/u (u=0 -> the current directory).
: FILES-DIR-LIST ( c-addr u -- ior )
  FILES-NAME! FILES-FN-DIR-LIST FILES-CALL ;

\ ---- user-facing disk words ------------------------------------------------
\ DIR [path]      list the current directory (or drive:path if given)
\ CATALOG [path]  alias for DIR
\ CD <path>       change the current drive/subdir   (e.g. CD fd0:games)
\ PWD             print the current drive:dir
: DIR ( "<path>" -- )
  PARSE-NAME FILES-DIR-LIST DROP ;
: CATALOG ( "<path>" -- )  DIR ;
: CD ( "<path>" -- )
  PARSE-NAME DUP 0= IF 2DROP EXIT THEN FILES-CD DROP ;
: PWD ( -- )
  FILES-PWD DROP TYPE CR ;

BASE !
