\ NovaForth wrappers for the NDK MEMORY module.
\ XRAM addresses are passed as xlo xhi: low 16 bits, then high byte.

INCLUDE forth/lib/nova/ndk.4th

BASE @
DECIMAL

0 CONSTANT MEM-FN-READ8
1 CONSTANT MEM-FN-WRITE8
2 CONSTANT MEM-FN-COPY-FROM-RAM
3 CONSTANT MEM-FN-COPY-TO-RAM
4 CONSTANT MEM-FN-FILL
5 CONSTANT MEM-FN-XLOAD
6 CONSTANT MEM-FN-XSAVE
7 CONSTANT MEM-FN-XMC-READ8
8 CONSTANT MEM-FN-XMC-WRITE8
9 CONSTANT MEM-FN-XMC-COPY-FROM-RAM
10 CONSTANT MEM-FN-XMC-COPY-TO-RAM
11 CONSTANT MEM-FN-XMC-FILL
12 CONSTANT MEM-FN-SELECT-BANK
13 CONSTANT MEM-FN-PUT-BYTE
14 CONSTANT MEM-FN-STASH-RAW
15 CONSTANT MEM-FN-FETCH-RAW
16 CONSTANT MEM-FN-RELEASE
17 CONSTANT MEM-FN-RESET-USAGE
18 CONSTANT MEM-FN-ALLOC
19 CONSTANT MEM-FN-NAMED-STASH
20 CONSTANT MEM-FN-NAMED-FETCH
21 CONSTANT MEM-FN-NAMED-DELETE
22 CONSTANT MEM-FN-DIR-OPEN
23 CONSTANT MEM-FN-DIR-READ
24 CONSTANT MEM-FN-MAP-WINDOW
25 CONSTANT MEM-FN-UNMAP-WINDOW
26 CONSTANT MEM-FN-COMMAND-STATUS
27 CONSTANT MEM-FN-COUNT

HEX
BA00 CONSTANT XMC-CMD
BA01 CONSTANT XMC-STATUS
BA02 CONSTANT XMC-ERRCODE
BA04 CONSTANT XMC-XAL
BA05 CONSTANT XMC-XAM
BA06 CONSTANT XMC-XAH
BA07 CONSTANT XMC-RAML
BA08 CONSTANT XMC-RAMH
BA09 CONSTANT XMC-LENL
BA0A CONSTANT XMC-LENH
BA0B CONSTANT XMC-DATA
BA0C CONSTANT XMC-BANK
BA0D CONSTANT XMC-BANKS
BA0E CONSTANT XMC-PAGES-USED
BA10 CONSTANT XMC-PAGES-FREE
BA12 CONSTANT XMC-NAMELEN
BA13 CONSTANT XMC-HANDLE
BA14 CONSTANT XMC-DIRCOUNT
BA16 CONSTANT XMC-WINCTL
BA18 CONSTANT XMC-WIN0
BA1B CONSTANT XMC-WIN1
BA1E CONSTANT XMC-WIN2
BA21 CONSTANT XMC-WIN3
BA24 CONSTANT XMC-NAME
DECIMAL

: MEMORY-CALL MODULE-MEMORY SWAP NOVA-LIBCALL ;

: MEM-COPY-ARGS! ( xlo xhi c-addr u -- )
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 NDK-U24! ;

: MEM-FILL-ARGS! ( xlo xhi u value -- )
  LIB-ARG3 C! LIB-ARG2 ! LIB-ARG0 NDK-U24! ;

: MEM-NAMED-ARGS! ( c-addr u ram len -- )
  LIB-ARG2 ! LIB-ARG1 2 + ! LIB-ARG1 C! LIB-ARG0 ! ;

: MEM-READ8 ( xlo xhi -- u ior )
  LIB-ARG0 NDK-U24!
  MEM-FN-READ8 MEMORY-CALL NDK-RESULT8 SWAP ;

: MEM-WRITE8 ( xlo xhi u -- ior )
  LIB-ARG3 C! LIB-ARG0 NDK-U24!
  MEM-FN-WRITE8 MEMORY-CALL ;

: MEM-COPY-FROM-RAM ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-COPY-FROM-RAM MEMORY-CALL ;

: MEM-COPY-TO-RAM ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-COPY-TO-RAM MEMORY-CALL ;

: MEM-FILL ( xlo xhi u value -- ior )
  MEM-FILL-ARGS!
  MEM-FN-FILL MEMORY-CALL ;

: MEM-XLOAD ( c-addr u xlo xhi len -- ior )
  LIB-ARG3 ! LIB-ARG2 NDK-U24! LIB-ARG1 C! LIB-ARG0 !
  MEM-FN-XLOAD MEMORY-CALL ;

: MEM-XSAVE ( c-addr u xlo xhi len -- ior )
  LIB-ARG3 ! LIB-ARG2 NDK-U24! LIB-ARG1 C! LIB-ARG0 !
  MEM-FN-XSAVE MEMORY-CALL ;

: MEM-XMC-READ8 ( xlo xhi -- u ior )
  LIB-ARG0 NDK-U24!
  MEM-FN-XMC-READ8 MEMORY-CALL NDK-RESULT8 SWAP ;

: MEM-XMC-WRITE8 ( xlo xhi u -- ior )
  LIB-ARG3 C! LIB-ARG0 NDK-U24!
  MEM-FN-XMC-WRITE8 MEMORY-CALL ;

: MEM-XMC-COPY-FROM-RAM ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-XMC-COPY-FROM-RAM MEMORY-CALL ;

: MEM-XMC-COPY-TO-RAM ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-XMC-COPY-TO-RAM MEMORY-CALL ;

: MEM-XMC-FILL ( xlo xhi u value -- ior )
  MEM-FILL-ARGS!
  MEM-FN-XMC-FILL MEMORY-CALL ;

: MEM-SELECT-BANK ( bank -- ior )
  LIB-ARG3 C!
  MEM-FN-SELECT-BANK MEMORY-CALL ;

: MEM-PUT-BYTE ( xlo xhi u -- ior )
  LIB-ARG3 C! LIB-ARG0 NDK-U24!
  MEM-FN-PUT-BYTE MEMORY-CALL ;

: MEM-STASH-RAW ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-STASH-RAW MEMORY-CALL ;

: MEM-FETCH-RAW ( xlo xhi c-addr u -- ior )
  MEM-COPY-ARGS!
  MEM-FN-FETCH-RAW MEMORY-CALL ;

: MEM-RELEASE ( xlo xhi u -- ior )
  LIB-ARG2 ! LIB-ARG0 NDK-U24!
  MEM-FN-RELEASE MEMORY-CALL ;

: MEM-RESET-USAGE ( -- ior )
  MEM-FN-RESET-USAGE MEMORY-CALL ;

: MEM-ALLOC ( u -- xlo xhi ior )
  LIB-ARG2 !
  MEM-FN-ALLOC MEMORY-CALL >R NDK-RESULT24 R> ;

: MEM-NAMED-STASH ( c-addr u ram len -- ior )
  MEM-NAMED-ARGS!
  MEM-FN-NAMED-STASH MEMORY-CALL ;

: MEM-NAMED-FETCH ( c-addr u ram len -- ior )
  MEM-NAMED-ARGS!
  MEM-FN-NAMED-FETCH MEMORY-CALL ;

: MEM-NAMED-DELETE ( c-addr u -- ior )
  LIB-ARG1 C! LIB-ARG0 !
  MEM-FN-NAMED-DELETE MEMORY-CALL ;

: MEM-DIR-OPEN ( -- ior )
  MEM-FN-DIR-OPEN MEMORY-CALL ;

: MEM-DIR-READ ( -- ior )
  MEM-FN-DIR-READ MEMORY-CALL ;

: MEM-MAP-WINDOW ( xlo window -- ior )
  LIB-ARG3 C! LIB-ARG0 !
  MEM-FN-MAP-WINDOW MEMORY-CALL ;

: MEM-UNMAP-WINDOW ( window -- ior )
  LIB-ARG3 C!
  MEM-FN-UNMAP-WINDOW MEMORY-CALL ;

: MEM-COMMAND-STATUS ( -- status ior )
  MEM-FN-COMMAND-STATUS MEMORY-CALL NDK-RESULT8 SWAP ;

BASE !
