\ NovaForth wrappers for the NDK SOUND module.

INCLUDE forth/lib/nova/ndk.4th

BASE @
DECIMAL

0 CONSTANT SND-FN-TONE
1 CONSTANT SND-FN-NOISE
2 CONSTANT SND-FN-VOLUME
3 CONSTANT SND-FN-PLAY-SOUND
4 CONSTANT SND-FN-SOUND
5 CONSTANT SND-FN-SET-VOLUME
6 CONSTANT SND-FN-INSTRUMENT
7 CONSTANT SND-FN-INIT
8 CONSTANT SND-FN-TICK
9 CONSTANT SND-FN-SIDPLAY
10 CONSTANT SND-FN-SIDSTOP
11 CONSTANT SND-FN-MIDPLAY
12 CONSTANT SND-FN-MIDSTOP
13 CONSTANT SND-FN-SFLOAD
14 CONSTANT SND-FN-SIDPLAY-FILE
15 CONSTANT SND-FN-MIDPLAY-FILE
16 CONSTANT SND-FN-SFLOAD-FILE
17 CONSTANT SND-FN-MUSIC-SEQUENCE
18 CONSTANT SND-FN-MUSIC-PLAY
19 CONSTANT SND-FN-MUSIC-STOP
20 CONSTANT SND-FN-MUSIC-TEMPO
21 CONSTANT SND-FN-MUSIC-LOOP
22 CONSTANT SND-FN-MUSIC-PRIORITY
23 CONSTANT SND-FN-STATUS
24 CONSTANT SND-FN-SFX-PLAYING
25 CONSTANT SND-FN-MUSIC-PLAYING
26 CONSTANT SND-FN-MUSIC-NOTE
27 CONSTANT SND-FN-COUNT

: SOUND-CALL MODULE-SOUND SWAP NOVA-LIBCALL ;

: SND-TONE ( freq dur -- ior )
  LIB-ARG1 ! LIB-ARG0 !
  SND-FN-TONE SOUND-CALL ;

: SND-NOISE ( dur -- ior )
  LIB-ARG0 !
  SND-FN-NOISE SOUND-CALL ;

: SND-VOLUME ( volume -- ior )
  LIB-ARG0 !
  SND-FN-VOLUME SOUND-CALL ;

: SND-PLAY-SOUND ( note dur instr -- ior )
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 !
  SND-FN-PLAY-SOUND SOUND-CALL ;

: SND-SOUND ( note dur instr -- ior )
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 !
  SND-FN-SOUND SOUND-CALL ;

: SND-SET-VOLUME ( volume voice -- ior )
  LIB-ARG1 ! LIB-ARG0 !
  SND-FN-SET-VOLUME SOUND-CALL ;

: SND-INSTRUMENT ( id wave attack decay sustain release -- ior )
  LIB-ARG3 2 + C!
  LIB-ARG3 1 + C!
  LIB-ARG3 C!
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 !
  SND-FN-INSTRUMENT SOUND-CALL ;

: SND-INIT ( -- ior )
  SND-FN-INIT SOUND-CALL ;

: SND-TICK ( -- ior )
  SND-FN-TICK SOUND-CALL ;

: SND-SIDPLAY ( song -- ior )
  LIB-ARG0 !
  SND-FN-SIDPLAY SOUND-CALL ;

: SND-SIDSTOP ( -- ior )
  SND-FN-SIDSTOP SOUND-CALL ;

: SND-MIDPLAY ( -- ior )
  SND-FN-MIDPLAY SOUND-CALL ;

: SND-MIDSTOP ( -- ior )
  SND-FN-MIDSTOP SOUND-CALL ;

: SND-SFLOAD ( -- ior )
  SND-FN-SFLOAD SOUND-CALL ;

: SND-SIDPLAY-FILE ( c-addr u song -- ior )
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 !
  SND-FN-SIDPLAY-FILE SOUND-CALL ;

: SND-MIDPLAY-FILE ( c-addr u -- ior )
  LIB-ARG1 ! LIB-ARG0 !
  SND-FN-MIDPLAY-FILE SOUND-CALL ;

: SND-SFLOAD-FILE ( c-addr u -- ior )
  LIB-ARG1 ! LIB-ARG0 !
  SND-FN-SFLOAD-FILE SOUND-CALL ;

: SND-MUSIC-SEQUENCE ( voice c-addr u -- ior )
  LIB-ARG2 ! LIB-ARG1 ! LIB-ARG0 !
  SND-FN-MUSIC-SEQUENCE SOUND-CALL ;

: SND-MUSIC-PLAY ( -- ior )
  SND-FN-MUSIC-PLAY SOUND-CALL ;

: SND-MUSIC-STOP ( -- ior )
  SND-FN-MUSIC-STOP SOUND-CALL ;

: SND-MUSIC-TEMPO ( bpm -- ior )
  LIB-ARG0 !
  SND-FN-MUSIC-TEMPO SOUND-CALL ;

: SND-MUSIC-LOOP ( flag -- ior )
  LIB-ARG0 !
  SND-FN-MUSIC-LOOP SOUND-CALL ;

: SND-MUSIC-PRIORITY ( priority -- ior )
  LIB-ARG0 !
  SND-FN-MUSIC-PRIORITY SOUND-CALL ;

: SND-STATUS ( -- status ior )
  SND-FN-STATUS SOUND-CALL NDK-RESULT8 SWAP ;

: SND-SFX-PLAYING ( -- flag ior )
  SND-FN-SFX-PLAYING SOUND-CALL NDK-RESULT8 SWAP ;

: SND-MUSIC-PLAYING ( -- flag ior )
  SND-FN-MUSIC-PLAYING SOUND-CALL NDK-RESULT8 SWAP ;

: SND-MUSIC-NOTE ( voice -- note ior )
  LIB-ARG0 !
  SND-FN-MUSIC-NOTE SOUND-CALL NDK-RESULT8 SWAP ;

BASE !
