\ NovaForth wrappers for the NDK TURTLE module.

INCLUDE forth/lib/nova/ndk.4th

BASE @
DECIMAL

HEX
A003 CONSTANT VGC-CURSX
A004 CONSTANT VGC-CURSY
A00A CONSTANT VGC-CURSEN
A00E CONSTANT VGC-CHAROUT
A0ED CONSTANT VGC-TEXT-TOPROW
A0EE CONSTANT VGC-TEXT-SCROLL-START
A0EF CONSTANT VGC-TEXT-SCROLL-ROWS
DECIMAL

40 CONSTANT TURTLE-TEXT-ROW
10 CONSTANT TURTLE-TEXT-ROWS
50 CONSTANT TURTLE-FULLTEXT-ROWS

0 CONSTANT TUR-FN-INIT
1 CONSTANT TUR-FN-DRAW
2 CONSTANT TUR-FN-ERASE
3 CONSTANT TUR-FN-OP
4 CONSTANT TUR-FN-COUNT

16 CONSTANT TOP-FD
17 CONSTANT TOP-BK
18 CONSTANT TOP-RT
19 CONSTANT TOP-LT
20 CONSTANT TOP-CS
21 CONSTANT TOP-PU
22 CONSTANT TOP-PD
23 CONSTANT TOP-ST
24 CONSTANT TOP-HT
25 CONSTANT TOP-HOME
26 CONSTANT TOP-TS
27 CONSTANT TOP-SS
28 CONSTANT TOP-FS
29 CONSTANT TOP-SETXY
30 CONSTANT TOP-SETX
31 CONSTANT TOP-SETY
32 CONSTANT TOP-SETH
33 CONSTANT TOP-XCOR
34 CONSTANT TOP-YCOR
35 CONSTANT TOP-HEADING
36 CONSTANT TOP-PENDOWNP
37 CONSTANT TOP-SHOWNP
38 CONSTANT TOP-SETPC
39 CONSTANT TOP-SETBG
40 CONSTANT TOP-TOWARDS

: TURTLE-CALL MODULE-TURTLE SWAP NOVA-LIBCALL ;

: TUR-INT! ( n addr -- )
  >R
  0 R@ C!
  DUP 255 AND R@ 1 + C!
  8 RSHIFT R> 2 + C! ;

: TUR-RESULT ( -- n )
  LIB-RESULT 1 + @ ;

: TUR-INIT ( -- ior )
  TUR-FN-INIT TURTLE-CALL ;

: TUR-DRAW ( x y angle -- ior )
  LIB-ARG2 C! LIB-ARG1 ! LIB-ARG0 !
  TUR-FN-DRAW TURTLE-CALL ;

: TUR-ERASE ( -- ior )
  TUR-FN-ERASE TURTLE-CALL ;

: TUR-OP ( op -- ior )
  LIB-ARG2 C!
  TUR-FN-OP TURTLE-CALL ;

: TUR-OP1 ( n op -- ior )
  >R LIB-ARG0 TUR-INT! R> TUR-OP ;

: TUR-OP2 ( x y op -- ior )
  >R LIB-ARG1 TUR-INT! LIB-ARG0 TUR-INT! R> TUR-OP ;

: TUR-OPBYTE ( u op -- ior )
  >R LIB-ARG0 C! R> TUR-OP ;

: TUR-REPORT0 ( op -- n ior )
  TUR-OP >R TUR-RESULT R> ;

: TUR-REPORT2 ( x y op -- n ior )
  TUR-OP2 >R TUR-RESULT R> ;

: TUR-FD ( n -- ior ) TOP-FD TUR-OP1 ;
: TUR-BK ( n -- ior ) TOP-BK TUR-OP1 ;
: TUR-RT ( n -- ior ) TOP-RT TUR-OP1 ;
: TUR-LT ( n -- ior ) TOP-LT TUR-OP1 ;
: TUR-CS ( -- ior ) TOP-CS TUR-OP ;
: TUR-PU ( -- ior ) TOP-PU TUR-OP ;
: TUR-PD ( -- ior ) TOP-PD TUR-OP ;
: TUR-ST ( -- ior ) TOP-ST TUR-OP ;
: TUR-HT ( -- ior ) TOP-HT TUR-OP ;
: TUR-HOME ( -- ior ) TOP-HOME TUR-OP ;
: TUR-TS ( -- ior ) TOP-TS TUR-OP ;
: TUR-SS ( -- ior ) TOP-SS TUR-OP ;
: TUR-FS ( -- ior ) TOP-FS TUR-OP ;
: TUR-SETXY ( x y -- ior ) TOP-SETXY TUR-OP2 ;
: TUR-SETX ( x -- ior ) TOP-SETX TUR-OP1 ;
: TUR-SETY ( y -- ior ) TOP-SETY TUR-OP1 ;
: TUR-SETH ( n -- ior ) TOP-SETH TUR-OP1 ;
: TUR-SETPC ( color -- ior ) TOP-SETPC TUR-OPBYTE ;
: TUR-SETBG ( color -- ior ) TOP-SETBG TUR-OPBYTE ;
: TUR-XCOR ( -- n ior ) TOP-XCOR TUR-REPORT0 ;
: TUR-YCOR ( -- n ior ) TOP-YCOR TUR-REPORT0 ;
: TUR-HEADING ( -- n ior ) TOP-HEADING TUR-REPORT0 ;
: TUR-PENDOWN? ( -- flag ior ) TOP-PENDOWNP TUR-REPORT0 ;
: TUR-SHOWN? ( -- flag ior ) TOP-SHOWNP TUR-REPORT0 ;
: TUR-TOWARDS ( x y -- n ior ) TOP-TOWARDS TUR-REPORT2 ;

: TURTLE-TEXTWIN ( -- )
  12 VGC-CHAROUT C!
  0 VGC-CURSX C!
  TURTLE-TEXT-ROW VGC-CURSY C!
  0 VGC-CURSEN C!
  0 VGC-TEXT-TOPROW C!
  TURTLE-TEXT-ROW VGC-TEXT-SCROLL-START C!
  TURTLE-TEXT-ROWS VGC-TEXT-SCROLL-ROWS C! ;

: TURTLE-FULLTEXT ( -- )
  0 VGC-TEXT-TOPROW C!
  0 VGC-TEXT-SCROLL-START C!
  TURTLE-FULLTEXT-ROWS VGC-TEXT-SCROLL-ROWS C! ;

: FD TUR-FD DROP ;
: BK TUR-BK DROP ;
: RT TUR-RT DROP ;
: LT TUR-LT DROP ;
: CS TUR-CS DROP TURTLE-TEXTWIN ;
: PU TUR-PU DROP ;
: PD TUR-PD DROP ;
: ST TUR-ST DROP ;
: HT TUR-HT DROP ;
: HOME TUR-HOME DROP ;
: TS TUR-TS DROP TURTLE-FULLTEXT ;
: SS TUR-SS DROP TURTLE-TEXTWIN ;
: FS TUR-FS DROP ;
: SETXY TUR-SETXY DROP ;
: SETX TUR-SETX DROP ;
: SETY TUR-SETY DROP ;
: SETH TUR-SETH DROP ;
: SETPC TUR-SETPC DROP ;
: SETBG TUR-SETBG DROP ;
: XCOR TUR-XCOR DROP ;
: YCOR TUR-YCOR DROP ;
: HEADING TUR-HEADING DROP ;
: PENDOWN? TUR-PENDOWN? DROP ;
: SHOWN? TUR-SHOWN? DROP ;
: TOWARDS TUR-TOWARDS DROP ;

BASE !
