// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_sid_chip;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_sid_chip* __PVT__top__DOT__sid1_inst;
    Vtop_sid_chip* __PVT__top__DOT__sid2_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(key_valid,0,0);
        VL_IN8(key_data,7,0);
        VL_IN8(irq_n,0,0);
        VL_IN8(nmi_n,0,0);
        VL_OUT8(vid_r,3,0);
        VL_OUT8(vid_g,3,0);
        VL_OUT8(vid_b,3,0);
        VL_OUT8(vid_hsync,0,0);
        VL_OUT8(vid_vsync,0,0);
        VL_OUT8(vid_de,0,0);
        VL_IN8(dbg_peek_en,0,0);
        VL_OUT8(dbg_peek_data,7,0);
        VL_IN8(dbg_poke_en,0,0);
        VL_IN8(dbg_poke_data,7,0);
        VL_IN8(dbg_pause,0,0);
        VL_OUT8(dbg_cpu_a,7,0);
        VL_OUT8(dbg_cpu_x,7,0);
        VL_OUT8(dbg_cpu_y,7,0);
        VL_OUT8(dbg_cpu_sp,7,0);
        VL_OUT8(dbg_cpu_flags,7,0);
        CData/*7:0*/ top__DOT__cpu_dout;
        CData/*0:0*/ top__DOT__cpu_we;
        CData/*7:0*/ top__DOT__cpu_din;
        CData/*0:0*/ top__DOT__ext_rom_active;
        CData/*0:0*/ top__DOT__xmc_reg_sel;
        CData/*0:0*/ top__DOT__xmc_win_sel;
        CData/*0:0*/ top__DOT__xmc_win_enabled;
        CData/*0:0*/ top__DOT__blt_reg_sel;
        CData/*0:0*/ top__DOT__sid1_reg_sel;
        CData/*0:0*/ top__DOT__sid2_reg_sel;
        CData/*0:0*/ top__DOT__clear_input;
        CData/*7:0*/ top__DOT__blt_ram_wdata;
        CData/*0:0*/ top__DOT__blt_ram_we;
        CData/*7:0*/ top__DOT__blt_xram_wdata;
        CData/*0:0*/ top__DOT__blt_xram_we;
        CData/*2:0*/ top__DOT__blt_vgc_space;
        CData/*7:0*/ top__DOT__blt_vgc_wdata;
        CData/*0:0*/ top__DOT__blt_vgc_we;
        CData/*7:0*/ top__DOT__blt_cpu_rdata;
        CData/*4:0*/ top__DOT__sid_clk_div;
        CData/*0:0*/ top__DOT__sid_ce_1m;
        CData/*7:0*/ top__DOT__sid_cfg_reg;
        CData/*0:0*/ top__DOT____Vcellinp__cpu_inst__RDY;
        CData/*7:0*/ top__DOT__vgc_dbg_rdata;
        CData/*7:0*/ top__DOT__tile_dma_data;
        CData/*7:0*/ top__DOT__blt_inst__DOT____Vlvbound_hf31f73b8__0;
        CData/*3:0*/ top__DOT__blt_inst__DOT__state;
        CData/*0:0*/ top__DOT__blt_inst__DOT__fill_mode;
        CData/*0:0*/ top__DOT__blt_inst__DOT__colorkey_mode;
        CData/*0:0*/ top__DOT__blt_inst__DOT__use_row_buffer;
        CData/*2:0*/ top__DOT__blt_inst__DOT__src_space;
        CData/*2:0*/ top__DOT__blt_inst__DOT__dst_space;
        CData/*7:0*/ top__DOT__blt_inst__DOT__fill_value;
        CData/*7:0*/ top__DOT__blt_inst__DOT__color_key;
        CData/*7:0*/ top__DOT__blt_inst__DOT__read_byte;
        CData/*0:0*/ top__DOT__blt_inst__DOT__read_valid;
        CData/*7:0*/ top__DOT__blt_inst__DOT__mem_read_data;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ABL;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ABH;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ADD;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__DIHOLD;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__DIMUX;
    };
    struct {
        CData/*7:0*/ top__DOT__cpu_inst__DOT__IRHOLD;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__IRHOLD_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__C;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__Z;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__I;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__D;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__V;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__N;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__AN;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__HC;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__AI;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__IR;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__CI;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__CO;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__NMI_edge;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__regsel;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__regfile;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__P;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__state;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__PC_inc;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__src_reg;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__dst_reg;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__index_y;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_reg;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__inc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__write_back;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_only;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adc_sbc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__compare;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__shift;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rotate;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__backwards;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cond_true;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__cond_code;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__shift_right;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__alu_shift_right;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__op;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adc_bcd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adj_bcd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__bit_ins;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__plp;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__php;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__clc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sec;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cld;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sed;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cli;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sei;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__clv;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__res;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__write_register;
        CData/*0:0*/ top__DOT__cpu_inst__DOT____Vcellinp__ALU__BCD;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__NMI_1;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__AI7;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__BI7;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_BI;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_h;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_HC;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h90cd3135__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h5a8b2575__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h28c4f18f__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hced7a248__0;
    };
    struct {
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h87c37a99__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h45978041__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hd4129f91__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_ha13cfb6b__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hde0d773d__1;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hde0d773d__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h5d6d955d__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h2b480197__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hb8130fd5__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_he1a62a70__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h3f27e46b__3;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h9f4406d7__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_haa426699__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hd5fa5e14__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hd5133de6__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hed509973__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hc84a7865__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_haf1931bd__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hafb21497__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h1cc62cc7__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h6e0ff81d__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h3f27e46b__2;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h3f27e46b__1;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h3f27e46b__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hc0a966b6__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hdecc4094__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h902d5c6a__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h9d27345d__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_hef6c2195__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h9d4d7d6f__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h652b6de2__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h45ddebd4__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT____Vlvbound_h3318332a__0;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__visible;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__in_text_area;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__cursor_x;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__cursor_y;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__fg_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__bg_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__border_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_color;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__mode;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_enable;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__char_in_reg;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__font_slot;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__scroll_offset;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__scroll_pending;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__scroll_col;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__fill_target;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__gt_char_idx;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__gt_char_len;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__gt_font_row;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__gt_font_col;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_scale;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_scale_x;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_scale_y;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_start_y;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_cur_char;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gt_font_byte;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__copper_enabled;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_target_list;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_active_list;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_pending_list;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__copper_loading;
    };
    struct {
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_load_src;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__fio_name_len;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_busy;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_op;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_cy;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__vgc_reg_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__char_ram_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__color_ram_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_reg_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_char_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_color_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_vgc_sel;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gfx_y;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__blink_count;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_blink;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_here;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h021f5fae__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h02fc01d7__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h67f0dfac__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_ha057723b__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h8898988b__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_ha3d87205__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h353a15af__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_hf7076230__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_hf26d05a2__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h8c784627__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h02aa0280__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h21da2949__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h17e6e432__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h3335cc4a__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_ha65a9a44__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h7ed4573b__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h9afe376d__0;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__tile_size16;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__mirror_mode;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__trans_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_state;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_nt;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_col_row;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_col_idx;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_data_valid;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_phase;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_r;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_g;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_sub;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_cidx;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_3;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_11;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_12;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_13;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_14;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_15;
        CData/*3:0*/ __VdfgRegularize_hebeb780c_0_19;
        CData/*4:0*/ __Vdly__top__DOT__sid_clk_div;
        CData/*5:0*/ __Vdly__top__DOT__cpu_inst__DOT__state;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactPhaseResult;
    };
    struct {
        CData/*0:0*/ __VnbaPhaseResult;
        VL_IN16(dbg_peek_addr,15,0);
        VL_IN16(dbg_poke_addr,15,0);
        VL_OUT16(dbg_cpu_pc,15,0);
        SData/*15:0*/ top__DOT__cpu_addr;
        SData/*15:0*/ top__DOT__blt_ram_addr;
        SData/*15:0*/ top__DOT__blt_vgc_addr;
        SData/*15:0*/ top__DOT__tile_dma_addr;
        SData/*15:0*/ top__DOT__blt_inst__DOT__width;
        SData/*15:0*/ top__DOT__blt_inst__DOT__height;
        SData/*15:0*/ top__DOT__blt_inst__DOT__src_stride;
        SData/*15:0*/ top__DOT__blt_inst__DOT__dst_stride;
        SData/*15:0*/ top__DOT__blt_inst__DOT__row;
        SData/*15:0*/ top__DOT__blt_inst__DOT__col;
        SData/*9:0*/ top__DOT__blt_inst__DOT__buf_idx;
        SData/*15:0*/ top__DOT__cpu_inst__DOT__PC;
        SData/*15:0*/ top__DOT__cpu_inst__DOT__PC_temp;
        SData/*8:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__h_count;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__v_count;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__fill_sp;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__gt_pen_x;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_count;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_index;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_load_idx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_x;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_y;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_x2;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_y2;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_dx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_dy;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_err;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_sx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_sy;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__cmd_cx;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__pixel_color;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__scroll_x;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__scroll_y;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_src;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_count;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_dst;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_0;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_4;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_5;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_6;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_8;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_9;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_10;
        VL_OUT(audio_l,17,0);
        VL_OUT(audio_r,17,0);
        IData/*18:0*/ top__DOT__xmc_addr;
        IData/*18:0*/ top__DOT__blt_xram_addr;
        IData/*23:0*/ top__DOT__blt_inst__DOT__src_base;
        IData/*23:0*/ top__DOT__blt_inst__DOT__dst_base;
        IData/*23:0*/ top__DOT__blt_inst__DOT__wrote_count;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__unnamedblk14__DOT__i;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__unnamedblk15__DOT__i;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__unnamedblk16__DOT__i;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__unnamedblk17__DOT__i;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*7:0*/, 65536> top__DOT__ram;
        VlUnpacked<CData/*7:0*/, 16384> top__DOT__basic_rom;
        VlUnpacked<CData/*7:0*/, 16384> top__DOT__ext_rom;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 524288> top__DOT__xram;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__xmc_regs;
        VlUnpacked<CData/*7:0*/, 25> top__DOT__blt_inst__DOT__regs;
        VlUnpacked<CData/*7:0*/, 1024> top__DOT__blt_inst__DOT__row_buf;
        VlUnpacked<CData/*7:0*/, 4> top__DOT__cpu_inst__DOT__AXYS;
        VlUnpacked<SData/*11:0*/, 16> top__DOT__vgc_inst__DOT__palette;
        VlUnpacked<CData/*7:0*/, 2000> top__DOT__vgc_inst__DOT__char_ram;
        VlUnpacked<CData/*7:0*/, 2000> top__DOT__vgc_inst__DOT__color_ram;
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__vgc_inst__DOT__font_rom;
        VlUnpacked<CData/*3:0*/, 64000> top__DOT__vgc_inst__DOT__gfx_ram;
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__vgc_inst__DOT__sprite_shapes;
        VlUnpacked<SData/*8:0*/, 16> top__DOT__vgc_inst__DOT__spr_x;
        VlUnpacked<CData/*7:0*/, 16> top__DOT__vgc_inst__DOT__spr_y;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_enable;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_flip_h;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_flip_v;
        VlUnpacked<CData/*1:0*/, 16> top__DOT__vgc_inst__DOT__spr_pri;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_shape;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__regs;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_trans;
        VlUnpacked<IData/*16:0*/, 512> top__DOT__vgc_inst__DOT__fill_stack;
        VlUnpacked<IData/*16:0*/, 32> top__DOT__vgc_inst__DOT__copper_pos;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_reg;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_val;
        VlUnpacked<IData/*16:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_pos;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_reg;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_val;
        VlUnpacked<SData/*8:0*/, 128> top__DOT__vgc_inst__DOT__copper_list_count;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__vgc_inst__DOT__fio_name;
        VlUnpacked<SData/*9:0*/, 16> top__DOT__vgc_inst__DOT__spr_dx;
        VlUnpacked<SData/*9:0*/, 16> top__DOT__vgc_inst__DOT__spr_dy;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_fx;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_fy;
        VlUnpacked<SData/*10:0*/, 16> top__DOT__vgc_inst__DOT__spr_sa;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_pix;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_vis;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__tile_inst__DOT__tregs;
        VlUnpacked<CData/*7:0*/, 25> top__DOT__vgc_inst__DOT__tile_inst__DOT__col_buffer;
        VlUnpacked<CData/*7:0*/, 32768> top__DOT__vgc_inst__DOT__tile_inst__DOT__tile_data;
        VlUnpacked<CData/*7:0*/, 4000> top__DOT__vgc_inst__DOT__tile_inst__DOT__nametable;
        VlUnpacked<CData/*7:0*/, 4000> top__DOT__vgc_inst__DOT__tile_inst__DOT__attr_table;
        VlUnpacked<SData/*11:0*/, 256> top__DOT__vgc_inst__DOT__tile_inst__DOT__pal_ram;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__1;
    };
    struct {
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 2000>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__char_ram;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 2000>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__color_ram;
    VlNBACommitQueue<VlUnpacked<CData/*3:0*/, 64000>, false, CData/*3:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__gfx_ram;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 2048>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__sprite_shapes;
    VlNBACommitQueue<VlUnpacked<SData/*8:0*/, 128>, false, SData/*8:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__copper_list_count;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 4000>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__tile_inst__DOT__nametable;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
