// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_sid_chip;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_sid_chip* __PVT__top__DOT__sid1_inst;
    Vtop_sid_chip* __PVT__top__DOT__sid2_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(key_valid,0,0);
        VL_IN8(key_data,7,0);
        VL_IN8(irq_n,0,0);
        VL_IN8(nmi_n,0,0);
        VL_OUT8(vid_r,3,0);
        VL_OUT8(vid_g,3,0);
        VL_OUT8(vid_b,3,0);
        VL_OUT8(vid_hsync,0,0);
        VL_OUT8(vid_vsync,0,0);
        VL_OUT8(vid_de,0,0);
        VL_IN8(dbg_peek_en,0,0);
        VL_OUT8(dbg_peek_data,7,0);
        VL_IN8(dbg_poke_en,0,0);
        VL_IN8(dbg_poke_data,7,0);
        VL_IN8(dbg_pause,0,0);
        VL_OUT8(dbg_cpu_a,7,0);
        VL_OUT8(dbg_cpu_x,7,0);
        VL_OUT8(dbg_cpu_y,7,0);
        VL_OUT8(dbg_cpu_sp,7,0);
        VL_OUT8(dbg_cpu_flags,7,0);
        CData/*7:0*/ top__DOT__cpu_dout;
        CData/*0:0*/ top__DOT__cpu_we;
        CData/*7:0*/ top__DOT__cpu_din;
        CData/*0:0*/ top__DOT__ext_rom_active;
        CData/*0:0*/ top__DOT__xmc_reg_sel;
        CData/*0:0*/ top__DOT__xmc_win_sel;
        CData/*0:0*/ top__DOT__xmc_win_enabled;
        CData/*0:0*/ top__DOT__blt_reg_sel;
        CData/*0:0*/ top__DOT__sid1_reg_sel;
        CData/*0:0*/ top__DOT__sid2_reg_sel;
        CData/*0:0*/ top__DOT__clear_input;
        CData/*7:0*/ top__DOT__tile_dma_data;
        CData/*7:0*/ top__DOT__blt_ram_wdata;
        CData/*0:0*/ top__DOT__blt_ram_we;
        CData/*7:0*/ top__DOT__blt_xram_wdata;
        CData/*0:0*/ top__DOT__blt_xram_we;
        CData/*2:0*/ top__DOT__blt_vgc_space;
        CData/*0:0*/ top__DOT__blt_vgc_we;
        CData/*0:0*/ top__DOT__blt_vgc_re;
        CData/*7:0*/ top__DOT__blt_cpu_rdata;
        CData/*4:0*/ top__DOT__sid_clk_div;
        CData/*0:0*/ top__DOT__sid_ce_1m;
        CData/*7:0*/ top__DOT__sid_cfg_reg;
        CData/*0:0*/ top__DOT____Vcellinp__cpu_inst__RDY;
        CData/*7:0*/ top__DOT__vgc_dbg_rdata;
        CData/*7:0*/ top__DOT__blt_inst__DOT____Vlvbound_hf31f73b8__0;
        CData/*3:0*/ top__DOT__blt_inst__DOT__state;
        CData/*0:0*/ top__DOT__blt_inst__DOT__fill_mode;
        CData/*0:0*/ top__DOT__blt_inst__DOT__colorkey_mode;
        CData/*0:0*/ top__DOT__blt_inst__DOT__use_row_buffer;
        CData/*2:0*/ top__DOT__blt_inst__DOT__src_space;
        CData/*2:0*/ top__DOT__blt_inst__DOT__dst_space;
        CData/*7:0*/ top__DOT__blt_inst__DOT__fill_value;
        CData/*7:0*/ top__DOT__blt_inst__DOT__color_key;
        CData/*7:0*/ top__DOT__blt_inst__DOT__read_byte;
        CData/*0:0*/ top__DOT__blt_inst__DOT__read_valid;
        CData/*7:0*/ top__DOT__blt_inst__DOT__mem_read_data;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ABL;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ABH;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ADD;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__DIHOLD;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__DIMUX;
    };
    struct {
        CData/*7:0*/ top__DOT__cpu_inst__DOT__IRHOLD;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__IRHOLD_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__C;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__Z;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__I;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__D;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__V;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__N;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__AN;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__HC;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__AI;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__IR;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__CI;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__CO;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__NMI_edge;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__regsel;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__regfile;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__P;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__state;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__PC_inc;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__src_reg;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__dst_reg;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__index_y;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_reg;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__inc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__write_back;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_only;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adc_sbc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__compare;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__shift;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rotate;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__backwards;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cond_true;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__cond_code;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__shift_right;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__alu_shift_right;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__op;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adc_bcd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__adj_bcd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__bit_ins;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__plp;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__php;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__clc;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sec;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cld;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sed;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__cli;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__sei;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__clv;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__res;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__write_register;
        CData/*0:0*/ top__DOT__cpu_inst__DOT____Vcellinp__ALU__BCD;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__NMI_1;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__AI7;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__BI7;
        CData/*7:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_BI;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_h;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp_HC;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__visible;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__in_text_area;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__visible_d1;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__visible_d2;
    };
    struct {
        CData/*0:0*/ top__DOT__vgc_inst__DOT__in_text_area_d1;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__in_text_area_d2;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__h_sync_area_d1;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__h_sync_area_d2;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__v_sync_area_d1;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__v_sync_area_d2;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__text_row;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__real_row;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__font_line;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__gfx_y;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__text_col_d1;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__text_col_d2;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__text_row_d1;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__text_row_d2;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__font_pixel_d1;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__font_pixel_d2;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__scroll_offset;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__char_a_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__char_a_we;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__char_a_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__color_a_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__color_a_we;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__color_a_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__font_a_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__char_b_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__color_b_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__font_b_dout;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_a_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__gfx_a_we;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_a_dout;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_b_dout;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__spr_a_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__spr_a_we;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__spr_a_dout;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__copper_enabled;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_target_list;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_active_list;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_pending_list;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__copper_loading;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__copper_load_src;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__copper_fire;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__copper_fire_reg;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__copper_fire_val;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__cursor_x;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__cursor_y;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__fg_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__bg_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__border_color;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_color;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__mode;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_enable;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__char_in_reg;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__font_slot;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__scroll_pending;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__scroll_col;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__fio_name_len;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_busy;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_op;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_cy;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__sprrow_count;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprrow_spr;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprrow_row;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__sprcopy_phase;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__memread_pending;
    };
    struct {
        CData/*2:0*/ top__DOT__vgc_inst__DOT__memread_space;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_char_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_char_we;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_color_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_color_we;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__cmd_gfx_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_gfx_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_gfx_re;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__cmd_spr_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_spr_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cmd_spr_re;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_cmd_valid;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_cmd_code;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__artist_gfx_wdata;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_gfx_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_gfx_re;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_font_re;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_busy;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__vgc_reg_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__spr_reg_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__char_ram_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__color_ram_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_reg_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_char_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_color_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_vgc_sel;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__dbg_rd_pending;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__dbg_rd_source;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__dbg_rd_latch;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__blt_rd_pending;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__blt_rd_space;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__blt_rd_latch;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_blt_rdata;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__vgc_tile_wdata;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__vgc_tile_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__vgc_tile_re;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_blt_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_blt_re;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_opaque_d1;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_opaque_d2;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__blink_count;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_blink;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__cursor_here;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__text_inst__DOT__char_mem__DOT____Vlvbound_hcad4ec09__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__text_inst__DOT__char_mem__DOT____Vlvbound_h3482bd38__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__text_inst__DOT__color_mem__DOT____Vlvbound_hcad4ec09__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__text_inst__DOT__color_mem__DOT____Vlvbound_h3482bd38__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_inst__DOT__gfx_mem__DOT____Vlvbound_h0a4ce44c__0;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__gfx_inst__DOT__gfx_mem__DOT____Vlvbound_h75f189da__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__op;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__cy;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__color;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__octant_count;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fs_a_we;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fill_target;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__paint_phase;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__paint_init;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__push_count;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_char_idx;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_len;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_font_row;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_font_col;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_scale;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_scale_x;
    };
    struct {
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_scale_y;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_start_y;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_cur_char;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_font_byte;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_font_pending;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_b_dout;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__slb_a_din;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__slb_a_we;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__slb_b_dout;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_state;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_idx;
        CData/*2:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_read_byte;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_y_line;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_flip_h;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_flip_v;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_pri_r;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_shape_r;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_trans_r;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_next_scanline;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_write_px;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__unnamedblk2__DOT__fy;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__unnamedblk3__DOT__fx;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__unnamedblk3__DOT__color;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__scanline_buf__DOT____Vlvbound_h7b43b104__0;
        CData/*6:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__scanline_buf__DOT____Vlvbound_he4591f03__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_ha768cd16__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_h67f0dfac__0;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____Vlvbound_hbbfa6b2d__0;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__tile_size16;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__mirror_mode;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__trans_color;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__td_din_a;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__td_we_a;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__td_dout_a;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__td_dout_b;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__nt_din_a;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__nt_we_a;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__nt_dout_b;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__at_din_a;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__at_we_a;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__at_dout_b;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__pr_addr_a;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__pr_we_a;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_state;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_nt;
        CData/*5:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_col_row;
        CData/*4:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_col_idx;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_data_valid;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_phase;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_r;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_g;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_sub;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_pal_cidx;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_fill_val;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_nt_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_at_we;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_pal_we;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_nt_din;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_at_din;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_pal_addr_reg;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__blt_tile_rd_pending;
        CData/*7:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__blt_tile_rd_latch;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_pix_in_x;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_pix_in_y;
    };
    struct {
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_tile_size16;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_tile_w;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_sample_x;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s1_sample_y;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s2_sub_pal;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s2_sample_x_lsb;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s2_tile_pri;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s2_color_idx;
        CData/*0:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s3_pixel_valid;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s3_color_idx;
        CData/*1:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s3_tile_pri;
        CData/*3:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__s3_trans_color;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_3;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_11;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_12;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_13;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_14;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_15;
        CData/*3:0*/ __VdfgRegularize_hebeb780c_0_19;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_25;
        CData/*4:0*/ __Vdly__top__DOT__sid_clk_div;
        CData/*5:0*/ __Vdly__top__DOT__cpu_inst__DOT__state;
        CData/*7:0*/ __VdlyVal__top__DOT__vgc_inst__DOT__tile_inst__DOT__attr_table_ram__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__top__DOT__vgc_inst__DOT__tile_inst__DOT__attr_table_ram__DOT__mem__v0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_IN16(dbg_peek_addr,15,0);
        VL_IN16(dbg_poke_addr,15,0);
        VL_OUT16(dbg_cpu_pc,15,0);
        SData/*15:0*/ top__DOT__cpu_addr;
        SData/*15:0*/ top__DOT__blt_ram_addr;
        SData/*15:0*/ top__DOT__blt_vgc_addr;
        SData/*15:0*/ top__DOT__tile_dma_addr;
        SData/*15:0*/ top__DOT__blt_inst__DOT__width;
        SData/*15:0*/ top__DOT__blt_inst__DOT__height;
        SData/*15:0*/ top__DOT__blt_inst__DOT__src_stride;
        SData/*15:0*/ top__DOT__blt_inst__DOT__dst_stride;
        SData/*15:0*/ top__DOT__blt_inst__DOT__row;
        SData/*15:0*/ top__DOT__blt_inst__DOT__col;
        SData/*9:0*/ top__DOT__blt_inst__DOT__buf_idx;
        SData/*15:0*/ top__DOT__cpu_inst__DOT__PC;
        SData/*15:0*/ top__DOT__cpu_inst__DOT__PC_temp;
        SData/*8:0*/ top__DOT__cpu_inst__DOT__ALU__DOT__temp;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__h_count;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__v_count;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__gfx_x_d1;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__gfx_x_d2;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__char_a_addr;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__color_a_addr;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__font_a_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__gfx_a_addr;
        SData/*8:0*/ top__DOT__vgc_inst__DOT____Vcellinp__artist_inst__cmd_x1;
        SData/*8:0*/ top__DOT__vgc_inst__DOT____Vcellinp__artist_inst__cmd_x0;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__spr_a_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__spr_enable_flat;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__spr_flip_h_flat;
    };
    struct {
        SData/*15:0*/ top__DOT__vgc_inst__DOT__spr_flip_v_flat;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_count;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_index;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__copper_load_idx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_x;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__cmd_y;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__cmd_cx;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__cmd_char_addr;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__cmd_color_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__cmd_gfx_addr;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__cmd_spr_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__artist_gfx_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__artist_gfx_raddr;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__artist_font_addr;
        SData/*14:0*/ top__DOT__vgc_inst__DOT__vgc_tile_addr;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__pixel_color;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_rgb_d1;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_rgb_d2;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__text_inst__DOT__char_b_addr;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__gfx_inst__DOT__gfx_b_addr;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__x;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__y;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__x2;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__y2;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__dx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__dy;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__err;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__sx;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__sy;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__cx;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fs_a_addr;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fs_b_addr;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fill_sp;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__gt_pen_x;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_b_addr;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__slb_a_addr;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_clear_x;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_eval_x_r;
        SData/*8:0*/ top__DOT__vgc_inst__DOT__sprite_inst__DOT__unnamedblk3__DOT__screen_x;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__scroll_x;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__scroll_y;
        SData/*14:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__td_addr_a;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__nt_addr_a;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__nt_addr_b;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__at_addr_a;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__pr_din_a;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__pr_dout_b;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_src;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_count;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_dst;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__dma_fill_addr;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_nt_addr;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_at_addr;
        SData/*11:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__cmd_pal_din;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT__world_y;
        SData/*15:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____VdfgRegularize_hb33eefcd_0_1;
        SData/*10:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____VdfgRegularize_hb33eefcd_0_2;
        SData/*9:0*/ top__DOT__vgc_inst__DOT__tile_inst__DOT____VdfgRegularize_hb33eefcd_0_3;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_0;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_4;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_5;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_6;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_8;
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_9;
    };
    struct {
        SData/*15:0*/ __VdfgRegularize_hebeb780c_0_10;
        SData/*11:0*/ __VdlyDim0__top__DOT__vgc_inst__DOT__tile_inst__DOT__attr_table_ram__DOT__mem__v0;
        VL_OUT(audio_l,17,0);
        VL_OUT(audio_r,17,0);
        IData/*18:0*/ top__DOT__xmc_addr;
        IData/*18:0*/ top__DOT__blt_xram_addr;
        IData/*23:0*/ top__DOT__blt_inst__DOT__src_base;
        IData/*23:0*/ top__DOT__blt_inst__DOT__dst_base;
        IData/*23:0*/ top__DOT__blt_inst__DOT__wrote_count;
        VlWide<16>/*511:0*/ top__DOT__vgc_inst__DOT__fio_name_flat;
        VlWide<5>/*143:0*/ top__DOT__vgc_inst__DOT__spr_x_flat;
        VlWide<4>/*127:0*/ top__DOT__vgc_inst__DOT__spr_y_flat;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__spr_pri_flat;
        VlWide<17>/*543:0*/ top__DOT__vgc_inst__DOT__copper_pos_flat;
        VlWide<8>/*255:0*/ top__DOT__vgc_inst__DOT__copper_reg_flat;
        VlWide<8>/*255:0*/ top__DOT__vgc_inst__DOT__copper_val_flat;
        IData/*31:0*/ top__DOT__vgc_inst__DOT__unnamedblk14__DOT__i;
        IData/*16:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fs_a_din;
        IData/*16:0*/ top__DOT__vgc_inst__DOT__artist_inst__DOT__fs_b_dout;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ top__DOT__vgc_inst__DOT__spr_shape_flat;
        QData/*63:0*/ top__DOT__vgc_inst__DOT__spr_trans_flat;
        VlUnpacked<CData/*7:0*/, 65536> top__DOT__ram;
        VlUnpacked<CData/*7:0*/, 16384> top__DOT__basic_rom;
        VlUnpacked<CData/*7:0*/, 16384> top__DOT__ext_rom;
        VlUnpacked<CData/*7:0*/, 524288> top__DOT__xram;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__xmc_regs;
        VlUnpacked<CData/*7:0*/, 25> top__DOT__blt_inst__DOT__regs;
        VlUnpacked<CData/*7:0*/, 1024> top__DOT__blt_inst__DOT__row_buf;
        VlUnpacked<CData/*7:0*/, 4> top__DOT__cpu_inst__DOT__AXYS;
        VlUnpacked<SData/*11:0*/, 16> top__DOT__vgc_inst__DOT__palette;
        VlUnpacked<SData/*8:0*/, 16> top__DOT__vgc_inst__DOT__spr_x;
        VlUnpacked<CData/*7:0*/, 16> top__DOT__vgc_inst__DOT__spr_y;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_enable;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_flip_h;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__spr_flip_v;
        VlUnpacked<CData/*1:0*/, 16> top__DOT__vgc_inst__DOT__spr_pri;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_shape;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__spr_trans;
        VlUnpacked<IData/*16:0*/, 32> top__DOT__vgc_inst__DOT__copper_pos;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_reg;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_val;
        VlUnpacked<IData/*16:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_pos;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_reg;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__copper_list_val;
        VlUnpacked<SData/*8:0*/, 128> top__DOT__vgc_inst__DOT__copper_list_count;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__regs;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__vgc_inst__DOT__fio_name;
        VlUnpacked<CData/*7:0*/, 8> top__DOT__vgc_inst__DOT__sprrow_data;
        VlUnpacked<CData/*7:0*/, 2000> top__DOT__vgc_inst__DOT__text_inst__DOT__char_mem__DOT__mem;
        VlUnpacked<CData/*7:0*/, 2000> top__DOT__vgc_inst__DOT__text_inst__DOT__color_mem__DOT__mem;
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__vgc_inst__DOT__text_inst__DOT__font_mem__DOT__mem;
        VlUnpacked<CData/*3:0*/, 64000> top__DOT__vgc_inst__DOT__gfx_inst__DOT__gfx_mem__DOT__mem;
        VlUnpacked<IData/*16:0*/, 4> top__DOT__vgc_inst__DOT__artist_inst__DOT__push_neighbors;
        VlUnpacked<IData/*16:0*/, 512> top__DOT__vgc_inst__DOT__artist_inst__DOT__fill_stack_mem__DOT__mem;
        VlUnpacked<SData/*8:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_x;
        VlUnpacked<CData/*7:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_y;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_enable;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_flip_h;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_flip_v;
        VlUnpacked<CData/*1:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_pri;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_shape;
        VlUnpacked<CData/*3:0*/, 16> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_trans;
        VlUnpacked<CData/*7:0*/, 8> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_row_data;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__vgc_inst__DOT__sprite_inst__DOT__spr_mem__DOT__mem;
        VlUnpacked<CData/*6:0*/, 320> top__DOT__vgc_inst__DOT__sprite_inst__DOT__scanline_buf__DOT__mem;
        VlUnpacked<IData/*16:0*/, 32> top__DOT__vgc_inst__DOT__copper_inst__DOT__copper_pos;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_inst__DOT__copper_reg;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__copper_inst__DOT__copper_val;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__vgc_inst__DOT__tile_inst__DOT__tregs;
        VlUnpacked<CData/*7:0*/, 25> top__DOT__vgc_inst__DOT__tile_inst__DOT__col_buffer;
        VlUnpacked<CData/*7:0*/, 32768> top__DOT__vgc_inst__DOT__tile_inst__DOT__tile_data_ram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__tile_inst__DOT__nametable_ram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 4096> top__DOT__vgc_inst__DOT__tile_inst__DOT__attr_table_ram__DOT__mem;
        VlUnpacked<SData/*11:0*/, 256> top__DOT__vgc_inst__DOT__tile_inst__DOT__pal_ram_inst__DOT__mem;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__0;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__0;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid1_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v1__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v2__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<SData/*15:0*/, 12> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__waveform_dac__DOT__bitsum__1;
        VlUnpacked<SData/*11:0*/, 8> __Vtrigprevexpr___TOP__top__DOT__sid2_inst____PVT__v3__DOT__envelope_dac__DOT__bitsum__1;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<SData/*8:0*/, 128>, false, SData/*8:0*/, 1> __VdlyCommitQueuetop__DOT__vgc_inst__DOT__copper_list_count;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
