apiVersion: v1
kind: Service
metadata:
  name: novavm-website
  namespace: novavm
  labels:
    app: novavm-website
    app.kubernetes.io/name: novavm-website
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: walker-heavy-industries
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: novavm-website
