PROJECT_TITLE := Deadline
PROJECT_LABEL := DEADLINE
PROJECT_SIZE_KB := 1440
PROJECT_STORY := $(PROJECT_DIR)/STORY.BIN
PROJECT_IMAGE := $(DIST_DIR)/$(PROJECT)/fd0.ndi
PROJECT_SMOKE_ARGS := --generic-boot --expect-time-status
