\ NovaForth core extensions library.
\ Keep ENVIRONMENT? CORE-EXT false until this file provides the complete
\ Forth-2012 Core Extensions word set.

0 CONSTANT FALSE
0 INVERT CONSTANT TRUE

: <> = 0= ;
: U> SWAP U< ;
: 0<> 0= 0= ;
: 0> 0 > ;
: WITHIN OVER - >R - R> U< ;
: /STRING DUP >R - SWAP R> + SWAP ;

: VALUE CREATE , DOES> @ ;
: BUFFER: CREATE ALLOT ;
84 BUFFER: PAD

: ERASE 0 FILL ;
: HOLDS BEGIN DUP WHILE 1- 2DUP + C@ HOLD REPEAT 2DROP ;

: .R
  >R
  DUP 0< DUP >R IF NEGATE THEN
  0 <# #S R> IF [CHAR] - HOLD THEN #>
  R> OVER - SPACES TYPE ;

: U.R
  >R
  0 <# #S #>
  R> OVER - SPACES TYPE ;

: CASE 0 ; IMMEDIATE
: OF POSTPONE OVER POSTPONE = POSTPONE IF POSTPONE DROP ; IMMEDIATE
: ENDOF POSTPONE ELSE ; IMMEDIATE
: ENDCASE POSTPONE DROP BEGIN ?DUP WHILE POSTPONE THEN REPEAT ; IMMEDIATE

: DEFER CREATE 0 , DOES> @ EXECUTE ;
: DEFER! >BODY ! ;
: DEFER@ >BODY @ ;
: IS
  ' >BODY STATE @
  IF POSTPONE LITERAL POSTPONE !
  ELSE !
  THEN ; IMMEDIATE
: ACTION-OF
  ' >BODY STATE @
  IF POSTPONE LITERAL POSTPONE @
  ELSE @
  THEN ; IMMEDIATE
