using Avalonia;
using Avalonia.Controls;
using Avalonia.Threading;
using e6502.NovaPanel.Layout;
using e6502.NovaPanel.Services;

namespace e6502.NovaPanel;

public partial class MainWindow : Window
{
    // ── State ─────────────────────────────────────────────────────────────

    private NovaConnection? _conn;
    private KeySender? _keySender;
    private DebugKeySink? _keySink;
    private bool _minSizeSet;
    private PanelSettings _settings = new();

    // ── Responsive state (test-visible) ──────────────────────────────────

    public SizeClass CurrentSizeClass { get; private set; } = SizeClass.Compact;

    // Test-facing visibility proxies — the x:Name fields are generated by Avalonia source gen
    public bool RailVisible => Rail.IsVisible;
    public bool BottomVisible => Bottom.IsVisible;

    // ── Construction ──────────────────────────────────────────────────────

    public MainWindow()
    {
        InitializeComponent();
        LoadSettings();
        WireEvents();
    }

    private void WireEvents()
    {
        // Keyboard token → key sender
        Keyboard.KeyActivated += token => _keySender?.Send(token);

        // ConnBar wiring
        Conn.ConnectRequested += Connect;
        Conn.DisconnectRequested += Disconnect;

        // Responsive: track window size changes
        SizeChanged += (_, _) => ApplyLayout(Bounds.Width, Bounds.Height);

        // Min-size + initial layout after first layout pass
        LayoutUpdated += OnFirstLayout;

        // Persist on close
        Closing += (_, _) => SaveSettings();
    }

    // ── Settings persistence ──────────────────────────────────────────────

    private void LoadSettings()
    {
        _settings = PanelSettings.Load();

        // Restore host (skip if empty — leave ConnBar default intact)
        if (!string.IsNullOrWhiteSpace(_settings.Host))
            Conn.SetHost(_settings.Host);

        // Restore window bounds; clamping to minimums happens after first layout
        // (MinWidth/MinHeight are set by SetMinimumSize which runs on LayoutUpdated).
        // Store the desired size so OnFirstLayout can apply them after minimums are known.
        _pendingWidth = _settings.Width > 0 ? _settings.Width : null;
        _pendingHeight = _settings.Height > 0 ? _settings.Height : null;
        _pendingX = _settings.X;
        _pendingY = _settings.Y;
    }

    private void SaveSettings()
    {
        _settings.Host = Conn.HostText;
        _settings.Width = Bounds.Width;
        _settings.Height = Bounds.Height;
        var pos = Position;
        _settings.X = pos.X;
        _settings.Y = pos.Y;
        _settings.Save();
    }

    // Deferred bounds from settings (applied after min-size is known)
    private double? _pendingWidth;
    private double? _pendingHeight;
    private double? _pendingX;
    private double? _pendingY;

    // ── Responsive layout ─────────────────────────────────────────────────

    private void ApplyLayout(double width, double height)
    {
        SizeClass sc = ResponsiveController.Classify(width, height);
        CurrentSizeClass = sc;

        switch (sc)
        {
            case SizeClass.Compact:
                Rail.IsVisible = false;
                Bottom.IsVisible = false;
                break;
            case SizeClass.Wide:
                Rail.IsVisible = true;
                Bottom.IsVisible = false;
                break;
            case SizeClass.Full:
                Rail.IsVisible = true;
                Bottom.IsVisible = true;
                break;
        }
    }

    /// <summary>Test seam: invoke ApplyLayout directly from tests.</summary>
    public void ApplyLayoutForTest(double w, double h) => ApplyLayout(w, h);

    // ── Min-size enforcement ──────────────────────────────────────────────

    private void OnFirstLayout(object? sender, EventArgs e)
    {
        if (_minSizeSet) return;
        _minSizeSet = true;

        LayoutUpdated -= OnFirstLayout;

        SetMinimumSize();

        // Apply saved bounds now that minimums are established
        ApplySavedBounds();

        // Apply initial layout at current window size
        ApplyLayout(Bounds.Width, Bounds.Height);
    }

    private void ApplySavedBounds()
    {
        if (_pendingWidth.HasValue && _pendingHeight.HasValue)
        {
            double w = Math.Max(_pendingWidth.Value, MinWidth);
            double h = Math.Max(_pendingHeight.Value, MinHeight);
            Width = w;
            Height = h;
        }

        if (_pendingX.HasValue && _pendingY.HasValue)
        {
            Position = new Avalonia.PixelPoint((int)_pendingX.Value, (int)_pendingY.Value);
        }
    }

    private void SetMinimumSize()
    {
        // Measure keyboard to get its natural size requirement
        Keyboard.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
        double kbWidth = Keyboard.DesiredSize.Width;
        double kbHeight = Keyboard.DesiredSize.Height;

        // ConnBar height
        Conn.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
        double connHeight = Conn.DesiredSize.Height;

        const double pad = 8;
        double computedMinW = Math.Max(MinWidth, kbWidth + pad);
        double computedMinH = Math.Max(MinHeight, connHeight + kbHeight + pad);

        // Guard headless zero-size: enforce a sensible floor so tests always pass
        if (computedMinW <= pad) computedMinW = 600;
        if (computedMinH <= pad) computedMinH = 240;

        MinWidth = computedMinW;
        MinHeight = computedMinH;
    }

    // ── Connection lifecycle ──────────────────────────────────────────────

    private async void Connect(string host)
    {
        Disconnect();

        _conn = new NovaConnection(host);

        // Wire panels' Connection property
        Conn.Connection = _conn;
        StatusPanelCtrl.Connection = _conn;
        DrivesPanelCtrl.Connection = _conn;
        RuntimePanelCtrl.Connection = _conn;
        DiskImagesPanelCtrl.Connection = _conn;
        LibraryPanelCtrl.Connection = _conn;
        ModulesPanelCtrl.Connection = _conn;

        // State/status callbacks — always marshal to UI thread
        _conn.StateChanged += s => Dispatcher.UIThread.Post(() => Conn.SetState(s));
        _conn.StatusUpdated += st => Dispatcher.UIThread.Post(() => OnStatus(st));

        // Key sink
        _keySink = new DebugKeySink(host);
        _keySender = new KeySender(_keySink);

        // Start background poll
        _conn.Start(TimeSpan.FromSeconds(2));

        // Fire-and-forget refreshes (guarded)
        _ = SafeRefreshAsync(DiskImagesPanelCtrl);
        _ = SafeRefreshAsync(LibraryPanelCtrl);
        _ = SafeRefreshAsync(ModulesPanelCtrl);
    }

    private void OnStatus(NovaStatus st)
    {
        StatusPanelCtrl.Update(st);
        DrivesPanelCtrl.Update(st);
        RuntimePanelCtrl.Update(st);
        Conn.Update(st);
    }

    private async void Disconnect()
    {
        if (_conn is not null)
        {
            await _conn.StopAsync();
            await _conn.DisposeAsync();
            _conn = null;
        }

        if (_keySender is not null)
        {
            await _keySender.DisposeAsync();
            _keySender = null;
        }

        _keySink?.Dispose();
        _keySink = null;

        // Clear panel connections
        Conn.Connection = null;
        StatusPanelCtrl.Connection = null;
        DrivesPanelCtrl.Connection = null;
        RuntimePanelCtrl.Connection = null;
        DiskImagesPanelCtrl.Connection = null;
        LibraryPanelCtrl.Connection = null;
        ModulesPanelCtrl.Connection = null;

        Conn.SetState(ConnectionState.Disconnected);
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private static async Task SafeRefreshAsync(Views.Panels.DiskImagesPanel p)
    {
        try { await p.RefreshAsync(); } catch { }
    }

    private static async Task SafeRefreshAsync(Views.Panels.LibraryPanel p)
    {
        try { await p.RefreshAsync(); } catch { }
    }

    private static async Task SafeRefreshAsync(Views.Panels.ModulesPanel p)
    {
        try { await p.RefreshAsync(); } catch { }
    }
}
