10 REM ================================
20 REM  MUSIC
30 REM   - SID CHIPTUNE
40 REM  NOVABASIC MML MUSIC ENGINE
50 REM ================================
60 PRINT CHR$(12)
70 MODE 1:COLOR 1,0:GCLS
80 REM -- SID INSTRUMENTS --
90 INSTRUMENT 1,64,0,6,5,4:REM PULSE HARPSICHORD
100 INSTRUMENT 2,32,0,8,7,3:REM SAW HARPSICHORD
110 REM -- VOICE 1: UPPER --
120 MUSIC 1,"T100I1O4L16@FL@F800,6@PS+B-8R8A8R>D/<F/B-/>D/F/B->DF/G/F/E/C/<A/GFRD/<F/B-/>D/F/B->DF/G/F/E/C/<A/GFEG-/E/D8F8E8G-/E/D8<F8RG/>C#GRG/>C#GRG/>C#EGC#<GRFD<B-FFD<B-FD<B-G<G<B->EG-<G-FD<B-F"
130 MUSIC 1,"FD<B-FD<B->E<E<B->DF<FF<AF<AEF<A>CEF<AB-D<B-B-D<B-<G<B-GF<B-FE<B-EFD<B-FFD<B-FD<B-G<G<B->EG-<G-FD<B-FFD<B-FD<B->E<E<B->DF<FREF<A>CEF<AB-D<B-B-D<B-B-D<B-R8R>EF<A>CEF<AB-D<B-B-D<B-<FB-G#"
140 MUSIC 1,"AA/E/AGGC/E>CEAED&D<A>C<A>AB->DB-GB->DGFB->DFC#>C#D>DD>DF<FF#<F#G<GG<GD<B-F<FAEAGEGFEFD>DEEEEF<FF#<F#G<GG<GE<AF<FB->DB-GB->DGFB->DFC#>C#D>DD>DF<FF#<F#G<GG<GD<B-F<F<A/E/AGGC/E>C"
150 MUSIC 1,"EAEDD<A>C<A>AB->DB-GB->DGFB->DFC#>C#D>DD>DF<FF#<F#G<GG<GD<B-F<FDC8<B-&B-/>C<B-8>DC8<B-&B-/>C<B-8B->C8D&D/GF8<B-8E8C8<A8E8<B-8D8G#8B-8E8C8<A8E8<B-8D8R8RD/<F/B-/>D/F/B->DF/G/F/E/C/<A/GF"
160 MUSIC 1,"RD/<F/B-/>D/F/B->DF/G/F/E/C/<A/GFEG-/E/D8F8E8G-/E/D8<F8RG/>C#GRG/>C#GRG/>C#EGC#<GRFD<B-FFD<B-FD<B-G<G<B->EG-<G-FD<B-FFD<B-FD<B->E<E<B->DF<FF<AF<AEF<A>CEF<AB-D<B-"
170 MUSIC 1,"B-D<B-<G<B-GF<B-FE<B-EFD<B-FFD<B-FD<B-G<G<B->EG-<G-FD<B-FFD<B-FD<B->E<E<B->DF<FREF<A>CEF<AB-D<B-B-D<B-B-D<B-RAEAAGF8A8A8G8F8F#8D8B-8>D8<A8>D4D4B-4>D4<A4>D4G>C<G>C<G>C<G>CC/<F/F#GG8"
180 MUSIC 1,"A8A8G8F8A8A8G8F8F#8G8>C8<G8>C8<G8>C8<G8>C8E8D8C8D8E8E8E8G8>C#8B-8>D8B-8>D8<A8>D4D4B-4>D4<A4>D4E4D4C4D4>C8.<B-&B-8B-8B-/AG8B-&B-/A/G>CEFF#G&GB-FB>E>CEB->E4E4>C4E4B-4>E4R>C<F>FA>C<G>GA"
190 MUSIC 1,"F>FA>C<G>GG>GA>CF>FF#>F#EEC>C<A>AB->EGB->EG/B-/<B-/<B-/>D/F/B->DFB-D<B->E<B-GE<B-G>C#B-B->DFB->DFB-D<B->E<B-GE<B-GE<B-GRAB-R>E<B-G<G<B->EG<GB-<B-B-<B-GEC<C<B->E<B->CECD<B-FD"
200 MUSIC 1,"D<B-FD<FD<B-FE<EFD<B-FFD<B-FFD<B-FDF>DCE>CFE<AFE<EFE<AFFE<AFFE<AFEGEDF>DFD<B-FE<EFD<B-FFD<B-FFD<B-FRE<B-G<G<B->EG<GB-<B-B-<B-GEC<C<B-G-E<B->C<G-ECD<B-FDD<B-FD<FD<B-FE<EFD<B-FFD<B-F"
210 MUSIC 1,"FD<B-FC<FDC8<B-&B-/>C<B-8>DC8<B-&B-/>C<B-8B->C8D&D/GF8<B-8E8C8<A8E8<B-8D8R8<B-8E8C8<A8E8<B-8D8@FS0"
220 REM -- VOICE 2: LOWER --
230 MUSIC 2,"I2O2L8@FL@F800,6@PS+B-F<FAB-<B->D<B-FF<FD<DC<CE<AFE<AF<F<FB-<B->D<B-FF<FD<DC<CE<AFE<AF<F<FEG-16/E16/DFEG-16/E16/D<FE/B-/>EB->EB->ER<B-FD<B-GE<B-G-E<B-G-E<B-FD<B-GC#<B-FD<B-FD"
240 MUSIC 2,"<AFC<AFC<AFC<AFC<B-FDEED<DC#<C#<B-FD<B-GE<B-G-E<B-G-E<B-FD<B-GC#<B-FDD<B-FC<CE<AF<F<FFAE<B-<B-D<DG<GF<FC>CFAEF<FFAE<B-<B-R>D<D<B<BA>C<C<FAEF<FFAEC>CFAEF<FFAE<B-<B-FB->DF<FFB->D"
250 MUSIC 2,"<B-<B-FB->DF<FFB->DC>CFAEF<FFAEC>CFAEF<FFAE<B-<B-FB->DF<FFB->D<B-<B-FB->DF<FFB->DC>CFAEF<FFAEC>CFAEF<FFAE<B-<B-FB->DF<FFB->D<B-<B-FB->DF<FFB->D<AB->DFAB->DFAB->DFAB->DF"
260 MUSIC 2,"GB->EGB->EG-B->EG-B->EFB->DFB->DFB->DFB->DG<GF<FB-<B-B<BG<GF<FB-<B-F<FB-<B->D<B-FF<FD<DC<CE<AFE<AF<F<FB-<B->D<B-FF<FD<DC<CE<AFE<AF<F<FEG-16/E16/DFEG-16/E16/D<FE/B-/>EB->EB->ER"
270 MUSIC 2,"<B-FD<B-GE<B-G-E<B-G-E<B-FD<B-GC#<B-FD<B-FD<AFC<AFC<AFC<AFC<B-FDEED<DC#<C#<B-FD<B-GE<B-G-E<B-G-E<B-FD<B-GC#<B-FDD<B-FC<C<FAEF<FFAE<B-<B-F<B-RAE>F<FB->D<A<B-<B->B->D<A"
280 MUSIC 2,"F<FB->D<A<B-<B->B->D<AEEB->EG<B-<B->B->EGEEB->EGB->EG<E<EF<FB->D<A<B-<B->B->D<AF<FB->D<A<B-<B->B->D<AEEB->EG<B-<B->B->EGEEB->EGEED-<D-C<CB->CE<E<EB->CEG<GB->CE<C<CB->CEF<FA>CFAAA>CF"
290 MUSIC 2,"F<FA>CFAAA>CFA<A>C<CEEF#<F#G<GEE<B-<B-G<GF<FAB->DO-110B-<B-AB->DEEG<GF<FE<EF<FAB->DO-115B-<B-AB->DEE<B->EB-<B-AB->EEGB->EO-116B-<B->GB->EEEGB->EG<GG-<G-F<FFB->D<B-<B-FB->DD>DF<FG<GG#<G#"
300 MUSIC 2,"A<AFAEF<FFAEC>CF<FG<GA<AB-<B-FB->DF<FFB->D<B-<B-AAG<GF<FEEGB->EO-128B-<B->GB->EG<GGB->EEEG-B->EO-128B->FB->DDFB->DF<FFB->DFAEAB->DFAB->DFAB->DFAB->DFGB->EGB->EG-B->EG-B->E"
310 MUSIC 2,"FB->DFB->DFB->DFB->DG<GF<FB-<B-<B-<B-G>GF>FB->B-@FS0"
320 VOLUME 15
330 MUSIC PLAY
