when:
  - event: tag

depends_on:
  - build-gate

labels:
  platform: linux/amd64

steps:
  - name: publish
    image: ghcr.io/barryw/novavm-ci:1
    commands:
      - dotnet publish e6502.Avalonia -c Release -r linux-x64 -o publish/avalonia
      - dotnet publish e6502.MCP -c Release -r linux-x64 -o publish/mcp

  - name: package
    image: ghcr.io/barryw/novavm-ci:1
    commands:
      - tar -czf "nova-vm-$CI_COMMIT_TAG-linux-x64.tar.gz" -C publish/avalonia .
      - tar -czf "nova-mcp-$CI_COMMIT_TAG-linux-x64.tar.gz" -C publish/mcp .

  - name: upload
    image: ghcr.io/barryw/novavm-ci:1
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - gh release upload "$CI_COMMIT_TAG" nova-vm-$CI_COMMIT_TAG-linux-x64.tar.gz nova-mcp-$CI_COMMIT_TAG-linux-x64.tar.gz --repo barryw/NovaVM
