when:
  - event: tag

depends_on:
  - build-gate

labels:
  platform: windows/amd64

steps:
  - name: publish
    image: powershell
    commands:
      - dotnet publish e6502.Avalonia -c Release -r win-x64 -o publish/avalonia
      - dotnet publish e6502.MCP -c Release -r win-x64 -o publish/mcp

  - name: package
    image: powershell
    commands:
      - |
        $TAG = $env:CI_COMMIT_TAG
        Compress-Archive -Path publish/avalonia/* -DestinationPath "nova-vm-$TAG-win-x64.zip"
        Compress-Archive -Path publish/mcp/* -DestinationPath "nova-mcp-$TAG-win-x64.zip"

  - name: upload
    image: powershell
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - |
        $TAG = $env:CI_COMMIT_TAG
        gh release upload "$TAG" "nova-vm-$TAG-win-x64.zip" "nova-mcp-$TAG-win-x64.zip" --repo barryw/NovaVM
