when:
  - event: tag

depends_on:
  - build-linux
  - build-macos
  - build-windows

labels:
  platform: linux/amd64

steps:
  - name: finalize
    image: ghcr.io/barryw/novavm-ci:1
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - gh release edit "$$CI_COMMIT_TAG" --draft=false --repo "$$CI_REPO"
