when:
  - event: tag

depends_on:
  - build-gate

labels:
  platform: linux/amd64

steps:
  - name: publish
    image: ghcr.io/barryw/novavm-ci:latest
    commands:
      - TAG="${CI_COMMIT_TAG}"
      - dotnet publish e6502.Avalonia -c Release -r linux-x64 -o publish/avalonia
      - dotnet publish e6502.MCP -c Release -r linux-x64 -o publish/mcp

  - name: package
    image: ghcr.io/barryw/novavm-ci:latest
    commands:
      - TAG="${CI_COMMIT_TAG}"
      - tar -czf "nova-vm-${TAG}-linux-x64.tar.gz" -C publish/avalonia .
      - tar -czf "nova-mcp-${TAG}-linux-x64.tar.gz" -C publish/mcp .

  - name: upload
    image: ghcr.io/barryw/novavm-ci:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - TAG="${CI_COMMIT_TAG}"
      - gh release upload "${TAG}" nova-vm-${TAG}-linux-x64.tar.gz nova-mcp-${TAG}-linux-x64.tar.gz --repo barryw/NovaVM
