when:
  - event: tag

labels:
  platform: linux/amd64

steps:
  - name: build-and-test
    image: ghcr.io/barryw/novavm-ci:1
    commands:
      - dotnet build -c Release
      - dotnet test -c Release --verbosity normal

  - name: create-release
    image: ghcr.io/barryw/novavm-ci:1
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - |
        TAG="$$CI_COMMIT_TAG"
        if gh release view "$${TAG}" --repo "$$CI_REPO" >/dev/null 2>&1; then
          echo "Release $${TAG} already exists, skipping creation"
        else
          gh release create "$${TAG}" \
            --repo "$$CI_REPO" \
            --draft \
            --generate-notes \
            --title "$${TAG}"
        fi
