PROJECT_TITLE := The Lurking Horror
PROJECT_LABEL := LURKING
PROJECT_SIZE_KB := 1440
PROJECT_STORY := $(PROJECT_DIR)/STORY.BIN
PROJECT_SOUNDS := $(LURKING_SOUNDS)
PROJECT_IMAGE := $(DIST_DIR)/$(PROJECT)/fd0.ndi
PROJECT_SMOKE_ARGS := --generic-boot --skip-manifest-check
