import Foundation
import PixelCanvasKit

enum Ca65ImageScope: String, CaseIterable, Identifiable, Sendable {
    case selectedImage
    case allImages

    var id: String { rawValue }

    var label: String {
        switch self {
        case .selectedImage:
            return "Selected Image"
        case .allImages:
            return "All Images"
        }
    }
}

enum Ca65ExportKind: String, CaseIterable, Identifiable, Sendable {
    case indexedBitmap
    case blitterRectangles
    case vSpriteRecords
    case hardwareSprites
    case bitMasks

    var id: String { rawValue }

    var label: String {
        switch self {
        case .indexedBitmap:
            return "Indexed Bitmap"
        case .blitterRectangles:
            return "Blitter Rects"
        case .vSpriteRecords:
            return "VSprite Records"
        case .hardwareSprites:
            return "Hardware Sprites"
        case .bitMasks:
            return "Bit Masks"
        }
    }

    var usesTransparentColor: Bool {
        switch self {
        case .indexedBitmap, .bitMasks:
            return false
        case .blitterRectangles, .vSpriteRecords, .hardwareSprites:
            return true
        }
    }
}

struct Ca65ExportOptions: Equatable, Sendable {
    var kind: Ca65ExportKind
    var scope: Ca65ImageScope
    var symbolPrefix: String
    var segmentName: String
    var transparentColor: UInt8

    init(kind: Ca65ExportKind = .blitterRectangles,
         scope: Ca65ImageScope = .allImages,
         symbolPrefix: String = "novadraw_images",
         segmentName: String = "RODATA",
         transparentColor: UInt8 = 2) {
        self.kind = kind
        self.scope = scope
        self.symbolPrefix = symbolPrefix
        self.segmentName = segmentName
        self.transparentColor = transparentColor & 0x0F
    }
}

enum Ca65ExportError: LocalizedError, Equatable {
    case noImages
    case invalidImageSize(name: String)
    case hardwareSpriteSize(width: Int, height: Int)

    var errorDescription: String? {
        switch self {
        case .noImages:
            return "There are no images to export."
        case .invalidImageSize(let name):
            return "\(name) does not match the document canvas size."
        case .hardwareSpriteSize(let width, let height):
            return "Hardware sprite ca65 export requires a canvas no larger than 16x16. This canvas is \(width)x\(height)."
        }
    }
}

enum Ca65Exporter {
    @MainActor
    static func encode(document: PixelDocument, options: Ca65ExportOptions) throws -> String {
        let images: [CanvasImage]
        switch options.scope {
        case .selectedImage:
            images = [document.images[document.selectedImageIndex]]
        case .allImages:
            images = document.images
        }
        return try encode(images: images, width: document.width, height: document.height, options: options)
    }

    static func encode(images: [CanvasImage],
                       width: Int,
                       height: Int,
                       options: Ca65ExportOptions) throws -> String {
        guard !images.isEmpty else { throw Ca65ExportError.noImages }
        try validate(images: images, width: width, height: height)

        let base = sanitizeSymbol(options.symbolPrefix, fallback: "novadraw_images")
        let segment = sanitizeSegment(options.segmentName)
        let transparentColor = options.transparentColor & 0x0F

        var output: [String] = []
        output.append("; Generated by NovaDraw.")
        output.append("; Format: \(options.kind.label)")
        output.append("; Canvas: \(width)x\(height), images: \(images.count)")
        if options.kind.usesTransparentColor {
            output.append("; Transparent color: $\(hexByte(transparentColor))")
        }
        output.append("")

        if let segment {
            output.append(".segment \"\(segment)\"")
            output.append("")
        }

        switch options.kind {
        case .indexedBitmap:
            emitIndexedBitmap(images: images, width: width, height: height, base: base, output: &output)
        case .blitterRectangles:
            emitBlitterRectangles(images: images, width: width, height: height, base: base, transparentColor: transparentColor, output: &output)
        case .vSpriteRecords:
            emitVSpriteRecords(images: images, width: width, height: height, base: base, transparentColor: transparentColor, output: &output)
        case .hardwareSprites:
            try emitHardwareSprites(images: images, width: width, height: height, base: base, transparentColor: transparentColor, output: &output)
        case .bitMasks:
            emitBitMasks(images: images, width: width, height: height, base: base, output: &output)
        }

        return output.joined(separator: "\n") + "\n"
    }

    private static func validate(images: [CanvasImage], width: Int, height: Int) throws {
        let pixelCount = width * height
        for image in images {
            guard image.pixels.count == pixelCount, image.paintedPixels.count == pixelCount else {
                throw Ca65ExportError.invalidImageSize(name: image.name)
            }
        }
    }

    private static func emitIndexedBitmap(images: [CanvasImage],
                                          width: Int,
                                          height: Int,
                                          base: String,
                                          output: inout [String]) {
        let labels = imageLabels(base: base, images: images)
        emitCommonEquates(base: base, width: width, height: height, count: images.count, output: &output)
        emitPointerTables(base: base, labels: labels, output: &output)

        for (index, image) in images.enumerated() {
            output.append("\(labels[index]):")
            emitRows(pixelRows(for: image, width: width, height: height, unpaintedColor: 0), rowWidth: width, output: &output)
            output.append("")
        }
    }

    private static func emitBlitterRectangles(images: [CanvasImage],
                                              width: Int,
                                              height: Int,
                                              base: String,
                                              transparentColor: UInt8,
                                              output: inout [String]) {
        let labels = imageLabels(base: base, images: images)
        emitBlitterEquates(base: base, width: width, height: height, transparentColor: transparentColor, output: &output)
        emitLowHighPointerTables(base: base, labels: labels, valuesPerLine: 3, output: &output)

        for (index, image) in images.enumerated() {
            output.append("\(labels[index]):")
            emitRows(pixelRows(for: image, width: width, height: height, unpaintedColor: transparentColor), rowWidth: width, output: &output)
            output.append("")
        }
    }

    private static func emitBlitterEquates(base: String,
                                           width: Int,
                                           height: Int,
                                           transparentColor: UInt8,
                                           output: inout [String]) {
        output.append("\(base)_width = \(width)")
        output.append("\(base)_height = \(height)")
        output.append("\(base)_stride = \(width)")
        output.append("\(base)_image_size = \(width * height)")
        output.append("\(base)_transparent = $\(hexByte(transparentColor))")
        output.append("")
    }

    private static func emitVSpriteRecords(images: [CanvasImage],
                                           width: Int,
                                           height: Int,
                                           base: String,
                                           transparentColor: UInt8,
                                           output: inout [String]) {
        let labels = imageLabels(base: base, images: images)
        emitCommonEquates(base: base, width: width, height: height, count: images.count, output: &output)
        output.append("\(base)_transparent = $\(hexByte(transparentColor))")
        output.append("\(base)_record_size = \(4 + width * height)")
        output.append("")
        emitPointerTables(base: base, labels: labels, output: &output)

        for (index, image) in images.enumerated() {
            output.append("\(labels[index]):")
            output.append("        .word \(width), \(height)")
            emitRows(pixelRows(for: image, width: width, height: height, unpaintedColor: transparentColor), rowWidth: width, output: &output)
            output.append("")
        }
    }

    private static func emitHardwareSprites(images: [CanvasImage],
                                            width: Int,
                                            height: Int,
                                            base: String,
                                            transparentColor: UInt8,
                                            output: inout [String]) throws {
        guard width <= 16, height <= 16 else {
            throw Ca65ExportError.hardwareSpriteSize(width: width, height: height)
        }

        let labels = imageLabels(base: base, images: images)
        output.append("\(base)_width = 16")
        output.append("\(base)_height = 16")
        output.append("\(base)_count = \(images.count)")
        output.append("\(base)_bytes_per_sprite = 128")
        output.append("\(base)_transparent = $\(hexByte(transparentColor))")
        output.append("")
        emitPointerTables(base: base, labels: labels, output: &output)

        for (index, image) in images.enumerated() {
            output.append("\(labels[index]):")
            let sprite = packedHardwareSpriteRows(for: image, width: width, height: height, transparentColor: transparentColor)
            emitRows(sprite, rowWidth: 8, output: &output)
            output.append("")
        }
    }

    private static func emitBitMasks(images: [CanvasImage],
                                     width: Int,
                                     height: Int,
                                     base: String,
                                     output: inout [String]) {
        let labels = imageLabels(base: "\(base)_mask", images: images)
        emitMaskEquates(base: base, width: width, height: height, count: images.count, output: &output)
        emitPointerTables(base: "\(base)_mask", labels: labels, output: &output)

        for (index, image) in images.enumerated() {
            output.append("\(labels[index]):")
            emitRows(bitMaskRows(for: image, width: width, height: height), rowWidth: maskBytesPerRow(width), radix: .binary, output: &output)
            output.append("")
        }
    }

    private static func emitCommonEquates(base: String,
                                          width: Int,
                                          height: Int,
                                          count: Int,
                                          output: inout [String]) {
        output.append("\(base)_width = \(width)")
        output.append("\(base)_height = \(height)")
        output.append("\(base)_count = \(count)")
        output.append("\(base)_stride = \(width)")
        output.append("\(base)_image_size = \(width * height)")
        output.append("")
    }

    private static func emitMaskEquates(base: String,
                                        width: Int,
                                        height: Int,
                                        count: Int,
                                        output: inout [String]) {
        output.append("\(base)_width = \(width)")
        output.append("\(base)_height = \(height)")
        output.append("\(base)_count = \(count)")
        output.append("\(base)_row_bytes = \(maskBytesPerRow(width))")
        output.append("\(base)_tail_bits = \(maskTailBits(width))")
        output.append("\(base)_mask_size = \(maskBytesPerRow(width) * height)")
        output.append("")
    }

    private static func emitPointerTables(base: String, labels: [String], output: inout [String]) {
        emitLowHighPointerTables(base: base, labels: labels, output: &output)
        output.append("\(base)_ptr:")
        for chunk in labels.chunked(by: 8) {
            output.append("        .word \(chunk.joined(separator: ", "))")
        }
        output.append("")
    }

    private static func emitLowHighPointerTables(base: String,
                                                labels: [String],
                                                valuesPerLine: Int = 8,
                                                output: inout [String]) {
        output.append("\(base)_lo:")
        emitSymbolBytes(labels, prefix: "<", valuesPerLine: valuesPerLine, output: &output)
        output.append("\(base)_hi:")
        emitSymbolBytes(labels, prefix: ">", valuesPerLine: valuesPerLine, output: &output)
        output.append("")
    }

    private static func emitRows(_ data: [UInt8],
                                 rowWidth: Int,
                                 radix: ByteRadix = .hex,
                                 output: inout [String]) {
        guard rowWidth > 0 else { return }
        let maxBytesPerLine = max(1, min(rowWidth, 16))
        var rowStart = 0
        while rowStart < data.count {
            let rowEnd = min(rowStart + rowWidth, data.count)
            var offset = rowStart
            while offset < rowEnd {
                let end = min(offset + maxBytesPerLine, rowEnd)
                let values = data[offset..<end].map { formatByte($0, radix: radix) }
                output.append("        .byte \(values.joined(separator: ", "))")
                offset = end
            }
            rowStart = rowEnd
        }
    }

    private static func emitSymbolBytes(_ labels: [String],
                                        prefix: String,
                                        valuesPerLine: Int = 8,
                                        output: inout [String]) {
        for chunk in labels.chunked(by: valuesPerLine) {
            let values = chunk.map { "\(prefix)\($0)" }
            output.append("        .byte \(values.joined(separator: ", "))")
        }
    }

    private static func pixelRows(for image: CanvasImage,
                                  width: Int,
                                  height: Int,
                                  unpaintedColor: UInt8) -> [UInt8] {
        var result = [UInt8](repeating: unpaintedColor & 0x0F, count: width * height)
        for index in 0..<result.count where image.paintedPixels[index] != 0 {
            result[index] = image.pixels[index] & 0x0F
        }
        return result
    }

    private static func packedHardwareSpriteRows(for image: CanvasImage,
                                                 width: Int,
                                                 height: Int,
                                                 transparentColor: UInt8) -> [UInt8] {
        var result: [UInt8] = []
        for y in 0..<16 {
            for x in stride(from: 0, to: 16, by: 2) {
                let left = packedPixel(image: image, x: x, y: y, width: width, height: height, transparentColor: transparentColor)
                let right = packedPixel(image: image, x: x + 1, y: y, width: width, height: height, transparentColor: transparentColor)
                result.append(left | (right << 4))
            }
        }
        return result
    }

    private static func packedPixel(image: CanvasImage,
                                    x: Int,
                                    y: Int,
                                    width: Int,
                                    height: Int,
                                    transparentColor: UInt8) -> UInt8 {
        guard x < width, y < height else { return transparentColor & 0x0F }
        let index = y * width + x
        guard image.paintedPixels[index] != 0 else { return transparentColor & 0x0F }
        return image.pixels[index] & 0x0F
    }

    private static func bitMaskRows(for image: CanvasImage, width: Int, height: Int) -> [UInt8] {
        packBitRows(width: width, height: height) { index in
            image.paintedPixels[index] != 0
        }
    }

    private static func packBitRows(width: Int,
                                    height: Int,
                                    isSet: (Int) -> Bool) -> [UInt8] {
        let bytesPerRow = maskBytesPerRow(width)
        var result = [UInt8](repeating: 0, count: bytesPerRow * height)
        for y in 0..<height {
            for x in 0..<width {
                let index = y * width + x
                guard isSet(index) else { continue }
                let byteIndex = y * bytesPerRow + x / 8
                let bit = 7 - (x % 8)
                result[byteIndex] |= UInt8(1 << bit)
            }
        }
        return result
    }

    private static func imageLabels(base: String, images: [CanvasImage]) -> [String] {
        let digits = max(2, String(images.count).count)
        var usedNames: [String: Int] = [:]
        return images.enumerated().map { index, image in
            let fallback = "image_\(String(format: "%0\(digits)d", index + 1))"
            let component = sanitizeSymbolComponent(image.name, fallback: fallback)
            let occurrence = usedNames[component, default: 0] + 1
            usedNames[component] = occurrence
            let uniqueComponent = occurrence == 1 ? component : "\(component)_\(occurrence)"
            return "\(base)_\(uniqueComponent)"
        }
    }

    private static func maskBytesPerRow(_ width: Int) -> Int {
        (width + 7) / 8
    }

    private static func maskTailBits(_ width: Int) -> Int {
        let remainder = width % 8
        return remainder == 0 ? 8 : remainder
    }

    private static func sanitizeSegment(_ raw: String) -> String? {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return trimmed.replacingOccurrences(of: "\"", with: "")
    }

    private static func sanitizeSymbol(_ raw: String, fallback: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_"))
        let scalars = raw.trimmingCharacters(in: .whitespacesAndNewlines).unicodeScalars
        var cleaned = String.UnicodeScalarView()
        let underscore = UnicodeScalar("_")
        for scalar in scalars {
            cleaned.append(allowed.contains(scalar) ? scalar : underscore)
        }

        var result = String(cleaned)
        if result.isEmpty {
            result = fallback
        }
        if let first = result.unicodeScalars.first, CharacterSet.decimalDigits.contains(first) {
            result = "_" + result
        }
        return result
    }

    private static func sanitizeSymbolComponent(_ raw: String, fallback: String) -> String {
        sanitizeSymbol(raw.lowercased(), fallback: fallback)
    }

    private enum ByteRadix {
        case hex
        case binary
    }

    private static func formatByte(_ value: UInt8, radix: ByteRadix) -> String {
        switch radix {
        case .hex:
            return "$\(hexByte(value))"
        case .binary:
            let bits = String(value, radix: 2)
            return "%" + String(repeating: "0", count: 8 - bits.count) + bits
        }
    }

    private static func hexByte(_ value: UInt8) -> String {
        String(format: "%02X", value)
    }
}

private extension Array {
    func chunked(by size: Int) -> [[Element]] {
        guard size > 0 else { return [self] }
        var result: [[Element]] = []
        var index = startIndex
        while index < endIndex {
            let end = self.index(index, offsetBy: size, limitedBy: endIndex) ?? endIndex
            result.append(Array(self[index..<end]))
            index = end
        }
        return result
    }
}
