PROJECT_TITLE := Zork III
PROJECT_LABEL := ZORK3
PROJECT_SIZE_KB := 1440
PROJECT_STORY := $(PROJECT_DIR)/STORY.BIN
PROJECT_IMAGE := $(DIST_DIR)/$(PROJECT)/fd0.ndi
PROJECT_SMOKE_ARGS := --generic-boot --expect-more
